#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014.
# However, it has been created with the help of the GungHo Consortium,
# whose members are identified at https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
# Author M. Hambley, Met Office
# Modified I. Kavcic, Met Office

'''
Installs PSyclone from a working copy to a specified location.

This is a very simple install script, not meant to recreat the functionality
of the standard Python install methods. It is supposed to be simple.
'''
from __future__ import print_function

import argparse
import os
import os.path
import shutil
import stat


def install(workingcopy, installroot):
    '''
    Performs the install.

    If the install directory does not exist it will be created. If it does
    exist an exception will be thrown.

    workingcopy [in] (string) Filename of the working copy to install from.
    installRoot [in] (string) Filename of directory into which to install.
    '''
    if not os.path.exists(installroot):
        os.makedirs(installroot)
    else:
        raise Exception('Installation directory already exists')

    ignores = shutil.ignore_patterns('tests')
    shutil.copytree(os.path.join(workingcopy, 'src'),
                    os.path.join(installroot, 'psyclone'),
                    ignore=ignores)

    os.mkdir(os.path.join(installroot, 'bin'))
    os.symlink(os.path.join(
                       os.path.relpath(os.path.join(installroot, 'psyclone'),
                                       os.path.join(installroot, 'bin')), 
                       'generator.py'),
               os.path.join(installroot, 'bin', 'psyclone'))
    os.chmod(os.path.join(installroot, 'psyclone', 'generator.py'),
             stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR |
             stat.S_IRGRP | stat.S_IXGRP |
             stat.S_IROTH | stat.S_IXOTH)


def _arguments():
    ''' Obtain the install directory from the command-line arguments and
    work out the location of the working copy from which to install '''
    parser = argparse.ArgumentParser(add_help=False,
                                     description='Install PSyclone to disc.')
    parser.add_argument('directory', help='Filename for installation root')
    parser.add_argument('-help', '-h', '--help', action='help')
    arguments = parser.parse_args()

    # Find out where the working copy is...
    scriptfilename = os.path.realpath(__file__)
    workingcopyfilename = os.path.dirname(os.path.dirname(scriptfilename))

    return workingcopyfilename, arguments.directory

if __name__ == '__main__':
    WORKINGCOPYFILENAME, INSTALLDIRECTORYFILENAME = _arguments()
    install(WORKINGCOPYFILENAME, INSTALLDIRECTORYFILENAME)
