# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2021-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

# This makefile triggers the corresponding make targets in all
# subdirectories.

EXAMPLES=$(wildcard full_example*) value_range_check

include ../../top_level.mk
