var annotated_dup =
[
    [ "psyclone", null, [
      [ "algGen", null, [
        [ "Alg", "classpsyclone_1_1algGen_1_1Alg.html", "classpsyclone_1_1algGen_1_1Alg" ],
        [ "NoInvokesError", "classpsyclone_1_1algGen_1_1NoInvokesError.html", "classpsyclone_1_1algGen_1_1NoInvokesError" ]
      ] ],
      [ "configuration", null, [
        [ "Config", "classpsyclone_1_1configuration_1_1Config.html", "classpsyclone_1_1configuration_1_1Config" ],
        [ "ConfigurationError", "classpsyclone_1_1configuration_1_1ConfigurationError.html", "classpsyclone_1_1configuration_1_1ConfigurationError" ],
        [ "DynConfig", "classpsyclone_1_1configuration_1_1DynConfig.html", "classpsyclone_1_1configuration_1_1DynConfig" ],
        [ "GOceanConfig", "classpsyclone_1_1configuration_1_1GOceanConfig.html", "classpsyclone_1_1configuration_1_1GOceanConfig" ]
      ] ],
      [ "dynamo0p1", null, [
        [ "DynamoInvokes", "classpsyclone_1_1dynamo0p1_1_1DynamoInvokes.html", "classpsyclone_1_1dynamo0p1_1_1DynamoInvokes" ],
        [ "DynamoPSy", "classpsyclone_1_1dynamo0p1_1_1DynamoPSy.html", "classpsyclone_1_1dynamo0p1_1_1DynamoPSy" ],
        [ "DynBuiltInCallFactory", "classpsyclone_1_1dynamo0p1_1_1DynBuiltInCallFactory.html", null ],
        [ "DynInvoke", "classpsyclone_1_1dynamo0p1_1_1DynInvoke.html", "classpsyclone_1_1dynamo0p1_1_1DynInvoke" ],
        [ "DynKern", "classpsyclone_1_1dynamo0p1_1_1DynKern.html", "classpsyclone_1_1dynamo0p1_1_1DynKern" ],
        [ "DynKernCallFactory", "classpsyclone_1_1dynamo0p1_1_1DynKernCallFactory.html", null ],
        [ "DynKernelArgument", "classpsyclone_1_1dynamo0p1_1_1DynKernelArgument.html", "classpsyclone_1_1dynamo0p1_1_1DynKernelArgument" ],
        [ "DynKernelArguments", "classpsyclone_1_1dynamo0p1_1_1DynKernelArguments.html", "classpsyclone_1_1dynamo0p1_1_1DynKernelArguments" ],
        [ "DynLoop", "classpsyclone_1_1dynamo0p1_1_1DynLoop.html", "classpsyclone_1_1dynamo0p1_1_1DynLoop" ],
        [ "DynSchedule", "classpsyclone_1_1dynamo0p1_1_1DynSchedule.html", "classpsyclone_1_1dynamo0p1_1_1DynSchedule" ]
      ] ],
      [ "dynamo0p3", null, [
        [ "ArgOrdering", "classpsyclone_1_1dynamo0p3_1_1ArgOrdering.html", "classpsyclone_1_1dynamo0p3_1_1ArgOrdering" ],
        [ "DynamoInvokes", "classpsyclone_1_1dynamo0p3_1_1DynamoInvokes.html", "classpsyclone_1_1dynamo0p3_1_1DynamoInvokes" ],
        [ "DynamoPSy", "classpsyclone_1_1dynamo0p3_1_1DynamoPSy.html", "classpsyclone_1_1dynamo0p3_1_1DynamoPSy" ],
        [ "DynArgDescriptor03", "classpsyclone_1_1dynamo0p3_1_1DynArgDescriptor03.html", "classpsyclone_1_1dynamo0p3_1_1DynArgDescriptor03" ],
        [ "DynFuncDescriptor03", "classpsyclone_1_1dynamo0p3_1_1DynFuncDescriptor03.html", "classpsyclone_1_1dynamo0p3_1_1DynFuncDescriptor03" ],
        [ "DynGlobalSum", "classpsyclone_1_1dynamo0p3_1_1DynGlobalSum.html", "classpsyclone_1_1dynamo0p3_1_1DynGlobalSum" ],
        [ "DynHaloExchange", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchange.html", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchange" ],
        [ "DynHaloExchangeEnd", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchangeEnd.html", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchangeEnd" ],
        [ "DynHaloExchangeStart", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchangeStart.html", "classpsyclone_1_1dynamo0p3_1_1DynHaloExchangeStart" ],
        [ "DynInterGrid", "classpsyclone_1_1dynamo0p3_1_1DynInterGrid.html", "classpsyclone_1_1dynamo0p3_1_1DynInterGrid" ],
        [ "DynInvoke", "classpsyclone_1_1dynamo0p3_1_1DynInvoke.html", "classpsyclone_1_1dynamo0p3_1_1DynInvoke" ],
        [ "DynInvokeBasisFns", "classpsyclone_1_1dynamo0p3_1_1DynInvokeBasisFns.html", "classpsyclone_1_1dynamo0p3_1_1DynInvokeBasisFns" ],
        [ "DynInvokeBoundaryConditions", "classpsyclone_1_1dynamo0p3_1_1DynInvokeBoundaryConditions.html", "classpsyclone_1_1dynamo0p3_1_1DynInvokeBoundaryConditions" ],
        [ "DynInvokeCMAOperators", "classpsyclone_1_1dynamo0p3_1_1DynInvokeCMAOperators.html", "classpsyclone_1_1dynamo0p3_1_1DynInvokeCMAOperators" ],
        [ "DynInvokeDofmaps", "classpsyclone_1_1dynamo0p3_1_1DynInvokeDofmaps.html", "classpsyclone_1_1dynamo0p3_1_1DynInvokeDofmaps" ],
        [ "DynInvokeStencil", "classpsyclone_1_1dynamo0p3_1_1DynInvokeStencil.html", "classpsyclone_1_1dynamo0p3_1_1DynInvokeStencil" ],
        [ "DynKern", "classpsyclone_1_1dynamo0p3_1_1DynKern.html", "classpsyclone_1_1dynamo0p3_1_1DynKern" ],
        [ "DynKernCallFactory", "classpsyclone_1_1dynamo0p3_1_1DynKernCallFactory.html", null ],
        [ "DynKernelArgument", "classpsyclone_1_1dynamo0p3_1_1DynKernelArgument.html", "classpsyclone_1_1dynamo0p3_1_1DynKernelArgument" ],
        [ "DynKernelArguments", "classpsyclone_1_1dynamo0p3_1_1DynKernelArguments.html", "classpsyclone_1_1dynamo0p3_1_1DynKernelArguments" ],
        [ "DynKernMetadata", "classpsyclone_1_1dynamo0p3_1_1DynKernMetadata.html", "classpsyclone_1_1dynamo0p3_1_1DynKernMetadata" ],
        [ "DynLoop", "classpsyclone_1_1dynamo0p3_1_1DynLoop.html", "classpsyclone_1_1dynamo0p3_1_1DynLoop" ],
        [ "DynMeshes", "classpsyclone_1_1dynamo0p3_1_1DynMeshes.html", "classpsyclone_1_1dynamo0p3_1_1DynMeshes" ],
        [ "DynSchedule", "classpsyclone_1_1dynamo0p3_1_1DynSchedule.html", "classpsyclone_1_1dynamo0p3_1_1DynSchedule" ],
        [ "DynStencil", "classpsyclone_1_1dynamo0p3_1_1DynStencil.html", "classpsyclone_1_1dynamo0p3_1_1DynStencil" ],
        [ "FSDescriptor", "classpsyclone_1_1dynamo0p3_1_1FSDescriptor.html", "classpsyclone_1_1dynamo0p3_1_1FSDescriptor" ],
        [ "FSDescriptors", "classpsyclone_1_1dynamo0p3_1_1FSDescriptors.html", "classpsyclone_1_1dynamo0p3_1_1FSDescriptors" ],
        [ "FunctionSpace", "classpsyclone_1_1dynamo0p3_1_1FunctionSpace.html", "classpsyclone_1_1dynamo0p3_1_1FunctionSpace" ],
        [ "HaloDepth", "classpsyclone_1_1dynamo0p3_1_1HaloDepth.html", "classpsyclone_1_1dynamo0p3_1_1HaloDepth" ],
        [ "HaloReadAccess", "classpsyclone_1_1dynamo0p3_1_1HaloReadAccess.html", "classpsyclone_1_1dynamo0p3_1_1HaloReadAccess" ],
        [ "HaloWriteAccess", "classpsyclone_1_1dynamo0p3_1_1HaloWriteAccess.html", "classpsyclone_1_1dynamo0p3_1_1HaloWriteAccess" ],
        [ "KernCallArgList", "classpsyclone_1_1dynamo0p3_1_1KernCallArgList.html", "classpsyclone_1_1dynamo0p3_1_1KernCallArgList" ],
        [ "KernStubArgList", "classpsyclone_1_1dynamo0p3_1_1KernStubArgList.html", "classpsyclone_1_1dynamo0p3_1_1KernStubArgList" ]
      ] ],
      [ "dynamo0p3_builtins", null, [
        [ "DynATimesXKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynATimesXKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynATimesXKern" ],
        [ "DynAXMinusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXMinusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXMinusYKern" ],
        [ "DynAXPlusBYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXPlusBYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXPlusBYKern" ],
        [ "DynAXPlusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXPlusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynAXPlusYKern" ],
        [ "DynBuiltIn", "classpsyclone_1_1dynamo0p3__builtins_1_1DynBuiltIn.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynBuiltIn" ],
        [ "DynBuiltInCallFactory", "classpsyclone_1_1dynamo0p3__builtins_1_1DynBuiltInCallFactory.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynBuiltInCallFactory" ],
        [ "DynIncATimesXKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncATimesXKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncATimesXKern" ],
        [ "DynIncAXPlusBYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXPlusBYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXPlusBYKern" ],
        [ "DynIncAXPlusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXPlusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXPlusYKern" ],
        [ "DynIncAXTimesYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXTimesYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncAXTimesYKern" ],
        [ "DynIncXDividebyYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXDividebyYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXDividebyYKern" ],
        [ "DynIncXMinusBYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXMinusBYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXMinusBYKern" ],
        [ "DynIncXMinusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXMinusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXMinusYKern" ],
        [ "DynIncXPlusBYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPlusBYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPlusBYKern" ],
        [ "DynIncXPlusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPlusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPlusYKern" ],
        [ "DynIncXPowintNKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPowintNKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPowintNKern" ],
        [ "DynIncXPowrealAKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPowrealAKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXPowrealAKern" ],
        [ "DynIncXTimesYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXTimesYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynIncXTimesYKern" ],
        [ "DynSetvalCKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSetvalCKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSetvalCKern" ],
        [ "DynSetvalXKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSetvalXKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSetvalXKern" ],
        [ "DynSumXKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSumXKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynSumXKern" ],
        [ "DynXDividebyYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXDividebyYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXDividebyYKern" ],
        [ "DynXInnerproductXKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXInnerproductXKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXInnerproductXKern" ],
        [ "DynXInnerproductYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXInnerproductYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXInnerproductYKern" ],
        [ "DynXMinusBYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXMinusBYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXMinusBYKern" ],
        [ "DynXMinusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXMinusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXMinusYKern" ],
        [ "DynXPlusYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXPlusYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXPlusYKern" ],
        [ "DynXTimesYKern", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXTimesYKern.html", "classpsyclone_1_1dynamo0p3__builtins_1_1DynXTimesYKern" ]
      ] ],
      [ "expression", null, [
        [ "BinaryOperator", "classpsyclone_1_1expression_1_1BinaryOperator.html", "classpsyclone_1_1expression_1_1BinaryOperator" ],
        [ "ExpressionNode", "classpsyclone_1_1expression_1_1ExpressionNode.html", "classpsyclone_1_1expression_1_1ExpressionNode" ],
        [ "FunctionVar", "classpsyclone_1_1expression_1_1FunctionVar.html", "classpsyclone_1_1expression_1_1FunctionVar" ],
        [ "Grouping", "classpsyclone_1_1expression_1_1Grouping.html", "classpsyclone_1_1expression_1_1Grouping" ],
        [ "LiteralArray", "classpsyclone_1_1expression_1_1LiteralArray.html", "classpsyclone_1_1expression_1_1LiteralArray" ],
        [ "NamedArg", "classpsyclone_1_1expression_1_1NamedArg.html", "classpsyclone_1_1expression_1_1NamedArg" ],
        [ "Slicing", "classpsyclone_1_1expression_1_1Slicing.html", "classpsyclone_1_1expression_1_1Slicing" ]
      ] ],
      [ "f2pygen", null, [
        [ "ACCDirective", "classpsyclone_1_1f2pygen_1_1ACCDirective.html", "classpsyclone_1_1f2pygen_1_1ACCDirective" ],
        [ "AllocateGen", "classpsyclone_1_1f2pygen_1_1AllocateGen.html", "classpsyclone_1_1f2pygen_1_1AllocateGen" ],
        [ "AssignGen", "classpsyclone_1_1f2pygen_1_1AssignGen.html", "classpsyclone_1_1f2pygen_1_1AssignGen" ],
        [ "BaseDeclGen", "classpsyclone_1_1f2pygen_1_1BaseDeclGen.html", "classpsyclone_1_1f2pygen_1_1BaseDeclGen" ],
        [ "BaseGen", "classpsyclone_1_1f2pygen_1_1BaseGen.html", "classpsyclone_1_1f2pygen_1_1BaseGen" ],
        [ "CallGen", "classpsyclone_1_1f2pygen_1_1CallGen.html", "classpsyclone_1_1f2pygen_1_1CallGen" ],
        [ "CharDeclGen", "classpsyclone_1_1f2pygen_1_1CharDeclGen.html", "classpsyclone_1_1f2pygen_1_1CharDeclGen" ],
        [ "CommentGen", "classpsyclone_1_1f2pygen_1_1CommentGen.html", "classpsyclone_1_1f2pygen_1_1CommentGen" ],
        [ "DeallocateGen", "classpsyclone_1_1f2pygen_1_1DeallocateGen.html", "classpsyclone_1_1f2pygen_1_1DeallocateGen" ],
        [ "DeclGen", "classpsyclone_1_1f2pygen_1_1DeclGen.html", "classpsyclone_1_1f2pygen_1_1DeclGen" ],
        [ "Directive", "classpsyclone_1_1f2pygen_1_1Directive.html", "classpsyclone_1_1f2pygen_1_1Directive" ],
        [ "DirectiveGen", "classpsyclone_1_1f2pygen_1_1DirectiveGen.html", "classpsyclone_1_1f2pygen_1_1DirectiveGen" ],
        [ "DoGen", "classpsyclone_1_1f2pygen_1_1DoGen.html", "classpsyclone_1_1f2pygen_1_1DoGen" ],
        [ "IfThenGen", "classpsyclone_1_1f2pygen_1_1IfThenGen.html", "classpsyclone_1_1f2pygen_1_1IfThenGen" ],
        [ "ImplicitNoneGen", "classpsyclone_1_1f2pygen_1_1ImplicitNoneGen.html", "classpsyclone_1_1f2pygen_1_1ImplicitNoneGen" ],
        [ "ModuleGen", "classpsyclone_1_1f2pygen_1_1ModuleGen.html", "classpsyclone_1_1f2pygen_1_1ModuleGen" ],
        [ "OMPDirective", "classpsyclone_1_1f2pygen_1_1OMPDirective.html", "classpsyclone_1_1f2pygen_1_1OMPDirective" ],
        [ "ProgUnitGen", "classpsyclone_1_1f2pygen_1_1ProgUnitGen.html", "classpsyclone_1_1f2pygen_1_1ProgUnitGen" ],
        [ "SelectionGen", "classpsyclone_1_1f2pygen_1_1SelectionGen.html", "classpsyclone_1_1f2pygen_1_1SelectionGen" ],
        [ "SubroutineGen", "classpsyclone_1_1f2pygen_1_1SubroutineGen.html", "classpsyclone_1_1f2pygen_1_1SubroutineGen" ],
        [ "TypeCase", "classpsyclone_1_1f2pygen_1_1TypeCase.html", "classpsyclone_1_1f2pygen_1_1TypeCase" ],
        [ "TypeDeclGen", "classpsyclone_1_1f2pygen_1_1TypeDeclGen.html", "classpsyclone_1_1f2pygen_1_1TypeDeclGen" ],
        [ "UseGen", "classpsyclone_1_1f2pygen_1_1UseGen.html", "classpsyclone_1_1f2pygen_1_1UseGen" ]
      ] ],
      [ "gocean0p1", null, [
        [ "GOBuiltInCallFactory", "classpsyclone_1_1gocean0p1_1_1GOBuiltInCallFactory.html", null ],
        [ "GOInvoke", "classpsyclone_1_1gocean0p1_1_1GOInvoke.html", "classpsyclone_1_1gocean0p1_1_1GOInvoke" ],
        [ "GOInvokes", "classpsyclone_1_1gocean0p1_1_1GOInvokes.html", "classpsyclone_1_1gocean0p1_1_1GOInvokes" ],
        [ "GOKern", "classpsyclone_1_1gocean0p1_1_1GOKern.html", "classpsyclone_1_1gocean0p1_1_1GOKern" ],
        [ "GOKernCallFactory", "classpsyclone_1_1gocean0p1_1_1GOKernCallFactory.html", null ],
        [ "GOKernelArgument", "classpsyclone_1_1gocean0p1_1_1GOKernelArgument.html", "classpsyclone_1_1gocean0p1_1_1GOKernelArgument" ],
        [ "GOKernelArguments", "classpsyclone_1_1gocean0p1_1_1GOKernelArguments.html", "classpsyclone_1_1gocean0p1_1_1GOKernelArguments" ],
        [ "GOLoop", "classpsyclone_1_1gocean0p1_1_1GOLoop.html", "classpsyclone_1_1gocean0p1_1_1GOLoop" ],
        [ "GOPSy", "classpsyclone_1_1gocean0p1_1_1GOPSy.html", "classpsyclone_1_1gocean0p1_1_1GOPSy" ],
        [ "GOSchedule", "classpsyclone_1_1gocean0p1_1_1GOSchedule.html", "classpsyclone_1_1gocean0p1_1_1GOSchedule" ]
      ] ],
      [ "gocean1p0", null, [
        [ "GO1p0Descriptor", "classpsyclone_1_1gocean1p0_1_1GO1p0Descriptor.html", "classpsyclone_1_1gocean1p0_1_1GO1p0Descriptor" ],
        [ "GOACCDataDirective", "classpsyclone_1_1gocean1p0_1_1GOACCDataDirective.html", "classpsyclone_1_1gocean1p0_1_1GOACCDataDirective" ],
        [ "GOBuiltInCallFactory", "classpsyclone_1_1gocean1p0_1_1GOBuiltInCallFactory.html", null ],
        [ "GOInvoke", "classpsyclone_1_1gocean1p0_1_1GOInvoke.html", "classpsyclone_1_1gocean1p0_1_1GOInvoke" ],
        [ "GOInvokes", "classpsyclone_1_1gocean1p0_1_1GOInvokes.html", "classpsyclone_1_1gocean1p0_1_1GOInvokes" ],
        [ "GOKern", "classpsyclone_1_1gocean1p0_1_1GOKern.html", "classpsyclone_1_1gocean1p0_1_1GOKern" ],
        [ "GOKernCallFactory", "classpsyclone_1_1gocean1p0_1_1GOKernCallFactory.html", null ],
        [ "GOKernelArgument", "classpsyclone_1_1gocean1p0_1_1GOKernelArgument.html", "classpsyclone_1_1gocean1p0_1_1GOKernelArgument" ],
        [ "GOKernelArguments", "classpsyclone_1_1gocean1p0_1_1GOKernelArguments.html", "classpsyclone_1_1gocean1p0_1_1GOKernelArguments" ],
        [ "GOKernelGridArgument", "classpsyclone_1_1gocean1p0_1_1GOKernelGridArgument.html", "classpsyclone_1_1gocean1p0_1_1GOKernelGridArgument" ],
        [ "GOKernelType1p0", "classpsyclone_1_1gocean1p0_1_1GOKernelType1p0.html", "classpsyclone_1_1gocean1p0_1_1GOKernelType1p0" ],
        [ "GOLoop", "classpsyclone_1_1gocean1p0_1_1GOLoop.html", "classpsyclone_1_1gocean1p0_1_1GOLoop" ],
        [ "GOPSy", "classpsyclone_1_1gocean1p0_1_1GOPSy.html", "classpsyclone_1_1gocean1p0_1_1GOPSy" ],
        [ "GOSchedule", "classpsyclone_1_1gocean1p0_1_1GOSchedule.html", "classpsyclone_1_1gocean1p0_1_1GOSchedule" ],
        [ "GOStencil", "classpsyclone_1_1gocean1p0_1_1GOStencil.html", "classpsyclone_1_1gocean1p0_1_1GOStencil" ]
      ] ],
      [ "gui", null, [
        [ "Bind", "classpsyclone_1_1gui_1_1Bind.html", "classpsyclone_1_1gui_1_1Bind" ],
        [ "CanvasControl", "classpsyclone_1_1gui_1_1CanvasControl.html", "classpsyclone_1_1gui_1_1CanvasControl" ],
        [ "PSyclone", "classpsyclone_1_1gui_1_1PSyclone.html", "classpsyclone_1_1gui_1_1PSyclone" ]
      ] ],
      [ "line_length", null, [
        [ "FortLineLength", "classpsyclone_1_1line__length_1_1FortLineLength.html", "classpsyclone_1_1line__length_1_1FortLineLength" ]
      ] ],
      [ "nemo", null, [
        [ "NemoFparser2ASTProcessor", "classpsyclone_1_1nemo_1_1NemoFparser2ASTProcessor.html", "classpsyclone_1_1nemo_1_1NemoFparser2ASTProcessor" ],
        [ "NemoIfBlock", "classpsyclone_1_1nemo_1_1NemoIfBlock.html", "classpsyclone_1_1nemo_1_1NemoIfBlock" ],
        [ "NemoIfClause", "classpsyclone_1_1nemo_1_1NemoIfClause.html", "classpsyclone_1_1nemo_1_1NemoIfClause" ],
        [ "NemoImplicitLoop", "classpsyclone_1_1nemo_1_1NemoImplicitLoop.html", "classpsyclone_1_1nemo_1_1NemoImplicitLoop" ],
        [ "NemoInvoke", "classpsyclone_1_1nemo_1_1NemoInvoke.html", "classpsyclone_1_1nemo_1_1NemoInvoke" ],
        [ "NemoInvokes", "classpsyclone_1_1nemo_1_1NemoInvokes.html", "classpsyclone_1_1nemo_1_1NemoInvokes" ],
        [ "NemoKern", "classpsyclone_1_1nemo_1_1NemoKern.html", "classpsyclone_1_1nemo_1_1NemoKern" ],
        [ "NemoLoop", "classpsyclone_1_1nemo_1_1NemoLoop.html", "classpsyclone_1_1nemo_1_1NemoLoop" ],
        [ "NemoPSy", "classpsyclone_1_1nemo_1_1NemoPSy.html", "classpsyclone_1_1nemo_1_1NemoPSy" ],
        [ "NemoSchedule", "classpsyclone_1_1nemo_1_1NemoSchedule.html", "classpsyclone_1_1nemo_1_1NemoSchedule" ]
      ] ],
      [ "parse", null, [
        [ "Arg", "classpsyclone_1_1parse_1_1Arg.html", "classpsyclone_1_1parse_1_1Arg" ],
        [ "BuiltInCall", "classpsyclone_1_1parse_1_1BuiltInCall.html", "classpsyclone_1_1parse_1_1BuiltInCall" ],
        [ "BuiltInKernelTypeFactory", "classpsyclone_1_1parse_1_1BuiltInKernelTypeFactory.html", "classpsyclone_1_1parse_1_1BuiltInKernelTypeFactory" ],
        [ "Descriptor", "classpsyclone_1_1parse_1_1Descriptor.html", "classpsyclone_1_1parse_1_1Descriptor" ],
        [ "DynDescriptor", "classpsyclone_1_1parse_1_1DynDescriptor.html", "classpsyclone_1_1parse_1_1DynDescriptor" ],
        [ "DynKernelType", "classpsyclone_1_1parse_1_1DynKernelType.html", "classpsyclone_1_1parse_1_1DynKernelType" ],
        [ "Element", "classpsyclone_1_1parse_1_1Element.html", "classpsyclone_1_1parse_1_1Element" ],
        [ "FileInfo", "classpsyclone_1_1parse_1_1FileInfo.html", "classpsyclone_1_1parse_1_1FileInfo" ],
        [ "FunctionSpace", "classpsyclone_1_1parse_1_1FunctionSpace.html", "classpsyclone_1_1parse_1_1FunctionSpace" ],
        [ "GODescriptor", "classpsyclone_1_1parse_1_1GODescriptor.html", "classpsyclone_1_1parse_1_1GODescriptor" ],
        [ "GOKernelType", "classpsyclone_1_1parse_1_1GOKernelType.html", "classpsyclone_1_1parse_1_1GOKernelType" ],
        [ "InvokeCall", "classpsyclone_1_1parse_1_1InvokeCall.html", "classpsyclone_1_1parse_1_1InvokeCall" ],
        [ "KernelCall", "classpsyclone_1_1parse_1_1KernelCall.html", "classpsyclone_1_1parse_1_1KernelCall" ],
        [ "KernelProcedure", "classpsyclone_1_1parse_1_1KernelProcedure.html", "classpsyclone_1_1parse_1_1KernelProcedure" ],
        [ "KernelType", "classpsyclone_1_1parse_1_1KernelType.html", "classpsyclone_1_1parse_1_1KernelType" ],
        [ "KernelTypeFactory", "classpsyclone_1_1parse_1_1KernelTypeFactory.html", "classpsyclone_1_1parse_1_1KernelTypeFactory" ],
        [ "ParsedCall", "classpsyclone_1_1parse_1_1ParsedCall.html", "classpsyclone_1_1parse_1_1ParsedCall" ],
        [ "ParseError", "classpsyclone_1_1parse_1_1ParseError.html", "classpsyclone_1_1parse_1_1ParseError" ],
        [ "TensorProductElement", "classpsyclone_1_1parse_1_1TensorProductElement.html", "classpsyclone_1_1parse_1_1TensorProductElement" ]
      ] ],
      [ "profiler", null, [
        [ "ProfileNode", "classpsyclone_1_1profiler_1_1ProfileNode.html", "classpsyclone_1_1profiler_1_1ProfileNode" ],
        [ "Profiler", "classpsyclone_1_1profiler_1_1Profiler.html", null ]
      ] ],
      [ "psyGen", null, [
        [ "ACCDataDirective", "classpsyclone_1_1psyGen_1_1ACCDataDirective.html", "classpsyclone_1_1psyGen_1_1ACCDataDirective" ],
        [ "ACCDirective", "classpsyclone_1_1psyGen_1_1ACCDirective.html", "classpsyclone_1_1psyGen_1_1ACCDirective" ],
        [ "ACCLoopDirective", "classpsyclone_1_1psyGen_1_1ACCLoopDirective.html", "classpsyclone_1_1psyGen_1_1ACCLoopDirective" ],
        [ "ACCParallelDirective", "classpsyclone_1_1psyGen_1_1ACCParallelDirective.html", "classpsyclone_1_1psyGen_1_1ACCParallelDirective" ],
        [ "Argument", "classpsyclone_1_1psyGen_1_1Argument.html", "classpsyclone_1_1psyGen_1_1Argument" ],
        [ "Arguments", "classpsyclone_1_1psyGen_1_1Arguments.html", "classpsyclone_1_1psyGen_1_1Arguments" ],
        [ "Array", "classpsyclone_1_1psyGen_1_1Array.html", "classpsyclone_1_1psyGen_1_1Array" ],
        [ "Assignment", "classpsyclone_1_1psyGen_1_1Assignment.html", "classpsyclone_1_1psyGen_1_1Assignment" ],
        [ "BinaryOperation", "classpsyclone_1_1psyGen_1_1BinaryOperation.html", "classpsyclone_1_1psyGen_1_1BinaryOperation" ],
        [ "BuiltIn", "classpsyclone_1_1psyGen_1_1BuiltIn.html", "classpsyclone_1_1psyGen_1_1BuiltIn" ],
        [ "Call", "classpsyclone_1_1psyGen_1_1Call.html", "classpsyclone_1_1psyGen_1_1Call" ],
        [ "CodeBlock", "classpsyclone_1_1psyGen_1_1CodeBlock.html", "classpsyclone_1_1psyGen_1_1CodeBlock" ],
        [ "DataAccess", "classpsyclone_1_1psyGen_1_1DataAccess.html", "classpsyclone_1_1psyGen_1_1DataAccess" ],
        [ "Directive", "classpsyclone_1_1psyGen_1_1Directive.html", "classpsyclone_1_1psyGen_1_1Directive" ],
        [ "DummyTransformation", "classpsyclone_1_1psyGen_1_1DummyTransformation.html", "classpsyclone_1_1psyGen_1_1DummyTransformation" ],
        [ "FieldNotFoundError", "classpsyclone_1_1psyGen_1_1FieldNotFoundError.html", "classpsyclone_1_1psyGen_1_1FieldNotFoundError" ],
        [ "Fparser2ASTProcessor", "classpsyclone_1_1psyGen_1_1Fparser2ASTProcessor.html", "classpsyclone_1_1psyGen_1_1Fparser2ASTProcessor" ],
        [ "GenerationError", "classpsyclone_1_1psyGen_1_1GenerationError.html", "classpsyclone_1_1psyGen_1_1GenerationError" ],
        [ "GlobalSum", "classpsyclone_1_1psyGen_1_1GlobalSum.html", "classpsyclone_1_1psyGen_1_1GlobalSum" ],
        [ "HaloExchange", "classpsyclone_1_1psyGen_1_1HaloExchange.html", "classpsyclone_1_1psyGen_1_1HaloExchange" ],
        [ "IfBlock", "classpsyclone_1_1psyGen_1_1IfBlock.html", "classpsyclone_1_1psyGen_1_1IfBlock" ],
        [ "IfClause", "classpsyclone_1_1psyGen_1_1IfClause.html", "classpsyclone_1_1psyGen_1_1IfClause" ],
        [ "InternalError", "classpsyclone_1_1psyGen_1_1InternalError.html", "classpsyclone_1_1psyGen_1_1InternalError" ],
        [ "Invoke", "classpsyclone_1_1psyGen_1_1Invoke.html", "classpsyclone_1_1psyGen_1_1Invoke" ],
        [ "Invokes", "classpsyclone_1_1psyGen_1_1Invokes.html", "classpsyclone_1_1psyGen_1_1Invokes" ],
        [ "Kern", "classpsyclone_1_1psyGen_1_1Kern.html", "classpsyclone_1_1psyGen_1_1Kern" ],
        [ "KernelArgument", "classpsyclone_1_1psyGen_1_1KernelArgument.html", "classpsyclone_1_1psyGen_1_1KernelArgument" ],
        [ "Literal", "classpsyclone_1_1psyGen_1_1Literal.html", "classpsyclone_1_1psyGen_1_1Literal" ],
        [ "Loop", "classpsyclone_1_1psyGen_1_1Loop.html", "classpsyclone_1_1psyGen_1_1Loop" ],
        [ "NameSpace", "classpsyclone_1_1psyGen_1_1NameSpace.html", "classpsyclone_1_1psyGen_1_1NameSpace" ],
        [ "NameSpaceFactory", "classpsyclone_1_1psyGen_1_1NameSpaceFactory.html", "classpsyclone_1_1psyGen_1_1NameSpaceFactory" ],
        [ "Node", "classpsyclone_1_1psyGen_1_1Node.html", "classpsyclone_1_1psyGen_1_1Node" ],
        [ "OMPDirective", "classpsyclone_1_1psyGen_1_1OMPDirective.html", "classpsyclone_1_1psyGen_1_1OMPDirective" ],
        [ "OMPDoDirective", "classpsyclone_1_1psyGen_1_1OMPDoDirective.html", "classpsyclone_1_1psyGen_1_1OMPDoDirective" ],
        [ "OMPParallelDirective", "classpsyclone_1_1psyGen_1_1OMPParallelDirective.html", "classpsyclone_1_1psyGen_1_1OMPParallelDirective" ],
        [ "OMPParallelDoDirective", "classpsyclone_1_1psyGen_1_1OMPParallelDoDirective.html", "classpsyclone_1_1psyGen_1_1OMPParallelDoDirective" ],
        [ "PSy", "classpsyclone_1_1psyGen_1_1PSy.html", "classpsyclone_1_1psyGen_1_1PSy" ],
        [ "PSyFactory", "classpsyclone_1_1psyGen_1_1PSyFactory.html", "classpsyclone_1_1psyGen_1_1PSyFactory" ],
        [ "Reference", "classpsyclone_1_1psyGen_1_1Reference.html", "classpsyclone_1_1psyGen_1_1Reference" ],
        [ "Schedule", "classpsyclone_1_1psyGen_1_1Schedule.html", "classpsyclone_1_1psyGen_1_1Schedule" ],
        [ "Transformation", "classpsyclone_1_1psyGen_1_1Transformation.html", "classpsyclone_1_1psyGen_1_1Transformation" ],
        [ "TransInfo", "classpsyclone_1_1psyGen_1_1TransInfo.html", "classpsyclone_1_1psyGen_1_1TransInfo" ]
      ] ],
      [ "transformations", null, [
        [ "ACCDataTrans", "classpsyclone_1_1transformations_1_1ACCDataTrans.html", "classpsyclone_1_1transformations_1_1ACCDataTrans" ],
        [ "ACCLoopTrans", "classpsyclone_1_1transformations_1_1ACCLoopTrans.html", "classpsyclone_1_1transformations_1_1ACCLoopTrans" ],
        [ "ACCParallelTrans", "classpsyclone_1_1transformations_1_1ACCParallelTrans.html", "classpsyclone_1_1transformations_1_1ACCParallelTrans" ],
        [ "ACCRoutineTrans", "classpsyclone_1_1transformations_1_1ACCRoutineTrans.html", "classpsyclone_1_1transformations_1_1ACCRoutineTrans" ],
        [ "ColourTrans", "classpsyclone_1_1transformations_1_1ColourTrans.html", "classpsyclone_1_1transformations_1_1ColourTrans" ],
        [ "Dynamo0p3AsyncHaloExchangeTrans", "classpsyclone_1_1transformations_1_1Dynamo0p3AsyncHaloExchangeTrans.html", "classpsyclone_1_1transformations_1_1Dynamo0p3AsyncHaloExchangeTrans" ],
        [ "Dynamo0p3ColourTrans", "classpsyclone_1_1transformations_1_1Dynamo0p3ColourTrans.html", "classpsyclone_1_1transformations_1_1Dynamo0p3ColourTrans" ],
        [ "Dynamo0p3OMPLoopTrans", "classpsyclone_1_1transformations_1_1Dynamo0p3OMPLoopTrans.html", "classpsyclone_1_1transformations_1_1Dynamo0p3OMPLoopTrans" ],
        [ "Dynamo0p3RedundantComputationTrans", "classpsyclone_1_1transformations_1_1Dynamo0p3RedundantComputationTrans.html", "classpsyclone_1_1transformations_1_1Dynamo0p3RedundantComputationTrans" ],
        [ "DynamoLoopFuseTrans", "classpsyclone_1_1transformations_1_1DynamoLoopFuseTrans.html", "classpsyclone_1_1transformations_1_1DynamoLoopFuseTrans" ],
        [ "DynamoOMPParallelLoopTrans", "classpsyclone_1_1transformations_1_1DynamoOMPParallelLoopTrans.html", "classpsyclone_1_1transformations_1_1DynamoOMPParallelLoopTrans" ],
        [ "GOceanLoopFuseTrans", "classpsyclone_1_1transformations_1_1GOceanLoopFuseTrans.html", "classpsyclone_1_1transformations_1_1GOceanLoopFuseTrans" ],
        [ "GOceanOMPLoopTrans", "classpsyclone_1_1transformations_1_1GOceanOMPLoopTrans.html", "classpsyclone_1_1transformations_1_1GOceanOMPLoopTrans" ],
        [ "GOceanOMPParallelLoopTrans", "classpsyclone_1_1transformations_1_1GOceanOMPParallelLoopTrans.html", "classpsyclone_1_1transformations_1_1GOceanOMPParallelLoopTrans" ],
        [ "GOConstLoopBoundsTrans", "classpsyclone_1_1transformations_1_1GOConstLoopBoundsTrans.html", "classpsyclone_1_1transformations_1_1GOConstLoopBoundsTrans" ],
        [ "GOLoopSwapTrans", "classpsyclone_1_1transformations_1_1GOLoopSwapTrans.html", "classpsyclone_1_1transformations_1_1GOLoopSwapTrans" ],
        [ "KernelModuleInlineTrans", "classpsyclone_1_1transformations_1_1KernelModuleInlineTrans.html", "classpsyclone_1_1transformations_1_1KernelModuleInlineTrans" ],
        [ "LoopFuseTrans", "classpsyclone_1_1transformations_1_1LoopFuseTrans.html", "classpsyclone_1_1transformations_1_1LoopFuseTrans" ],
        [ "MoveTrans", "classpsyclone_1_1transformations_1_1MoveTrans.html", "classpsyclone_1_1transformations_1_1MoveTrans" ],
        [ "OCLTrans", "classpsyclone_1_1transformations_1_1OCLTrans.html", "classpsyclone_1_1transformations_1_1OCLTrans" ],
        [ "OMPLoopTrans", "classpsyclone_1_1transformations_1_1OMPLoopTrans.html", "classpsyclone_1_1transformations_1_1OMPLoopTrans" ],
        [ "OMPParallelLoopTrans", "classpsyclone_1_1transformations_1_1OMPParallelLoopTrans.html", "classpsyclone_1_1transformations_1_1OMPParallelLoopTrans" ],
        [ "OMPParallelTrans", "classpsyclone_1_1transformations_1_1OMPParallelTrans.html", "classpsyclone_1_1transformations_1_1OMPParallelTrans" ],
        [ "ParallelLoopTrans", "classpsyclone_1_1transformations_1_1ParallelLoopTrans.html", "classpsyclone_1_1transformations_1_1ParallelLoopTrans" ],
        [ "ParallelRegionTrans", "classpsyclone_1_1transformations_1_1ParallelRegionTrans.html", "classpsyclone_1_1transformations_1_1ParallelRegionTrans" ],
        [ "ProfileRegionTrans", "classpsyclone_1_1transformations_1_1ProfileRegionTrans.html", "classpsyclone_1_1transformations_1_1ProfileRegionTrans" ],
        [ "RegionTrans", "classpsyclone_1_1transformations_1_1RegionTrans.html", null ],
        [ "TransformationError", "classpsyclone_1_1transformations_1_1TransformationError.html", "classpsyclone_1_1transformations_1_1TransformationError" ]
      ] ],
      [ "undoredo", null, [
        [ "Memento", "classpsyclone_1_1undoredo_1_1Memento.html", "classpsyclone_1_1undoredo_1_1Memento" ],
        [ "UR", "classpsyclone_1_1undoredo_1_1UR.html", "classpsyclone_1_1undoredo_1_1UR" ]
      ] ]
    ] ]
];