PSyclone: psyclone.dynamo0p3.DynInvokeStencil Class Reference
psyclone.dynamo0p3.DynInvokeStencil Class Reference
Public Member Functions
def __init__ (self, schedule)
def unique_alg_vars (self)
def declare_unique_alg_vars (self, parent)
def initialise_stencil_maps (self, parent)
Detailed Description
stencil information and code generation associated with a
DynInvoke call
Definition at line 1442 of file dynamo0p3.py.
Member Function Documentation
def psyclone.dynamo0p3.DynInvokeStencil.declare_unique_alg_vars (self, parent)
declares all extent and direction arguments passed into the PSy
layer
Definition at line 1545 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynInvokeStencil._declare_unique_direction_vars(), and psyclone.dynamo0p3.DynInvokeStencil._declare_unique_extent_vars().
     def declare_unique_alg_vars(self, parent):
         '''declares all extent and direction arguments passed into the PSy
         layer'''
         self._declare_unique_extent_vars(parent)
         self._declare_unique_direction_vars(parent)
def psyclone.dynamo0p3.DynInvokeStencil.initialise_stencil_maps (self, parent)
adds in the required stencil dofmap code to the PSy layer
Definition at line 1551 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynInvokeStencil._kern_args.
     def initialise_stencil_maps(self, parent):
         '''adds in the required stencil dofmap code to the PSy layer'''
         from psyclone.f2pygen import AssignGen, IfThenGen, TypeDeclGen, \
             UseGen, CommentGen, DeclGen
         if self._kern_args:
             parent.add(CommentGen(parent, ""))
             parent.add(CommentGen(parent, " Initialise stencil dofmaps"))
             parent.add(CommentGen(parent, ""))
             parent.add(UseGen(parent, name="stencil_dofmap_mod", only=True,
                               funcnames=["stencil_dofmap_type"]))
             stencil_map_names = []
             for arg in self._kern_args:
                 map_name = stencil_map_name(arg)
                 if map_name not in stencil_map_names:
                     # only initialise maps once
                     stencil_map_names.append(map_name)
                     parent.add(
                         TypeDeclGen(parent, pointer=True,
                                     datatype="stencil_dofmap_type",
                                     entity_decls=[map_name+" => null()"]))
                     stencil_type = arg.descriptor.stencil['type']
                     if stencil_type == "xory1d":
                         parent.add(UseGen(parent, name="flux_direction_mod",
                                           only=True,
                                           funcnames=["x_direction",
                                                      "y_direction"]))
                         parent.add(UseGen(parent, name="stencil_dofmap_mod",
                                           only=True,
                                           funcnames=["STENCIL_1DX",
                                                      "STENCIL_1DY"]))
                         direction_name = arg.stencil.direction_arg.varName
                         for direction in ["x", "y"]:
                             if_then = IfThenGen(parent, direction_name +
                                                 " .eq. " + direction +
                                                 "_direction")
                             if_then.add(
                                 AssignGen(if_then, pointer=True,
                                           lhs=map_name, rhs=arg.proxy_name +
                                           "%vspace%get_stencil_dofmap("
                                           "STENCIL_1D" + direction.upper() +
                                           ","+stencil_extent_value(arg)+")"))
                             parent.add(if_then)
                     else:
                         try:
                             stencil_name = STENCIL_MAPPING[stencil_type]
                         except KeyError:
                             raise GenerationError(
                                 "Unsupported stencil type '{0}' supplied. "
                                 "Supported mappings are {1}".
                                 format(arg.descriptor.stencil['type'],
                                        str(STENCIL_MAPPING)))
                         parent.add(UseGen(parent, name="stencil_dofmap_mod",
                                           only=True,
                                           funcnames=[stencil_name]))
                         parent.add(
                             AssignGen(parent, pointer=True, lhs=map_name,
                                       rhs=arg.proxy_name +
                                       "%vspace%get_stencil_dofmap(" +
                                       stencil_name + "," +
                                       stencil_extent_value(arg) + ")"))
                     parent.add(DeclGen(parent, datatype="integer",
                                        pointer=True,
                                        entity_decls=[stencil_dofmap_name(arg) +
                                                      "(:,:,:) => null()"]))
                     parent.add(AssignGen(parent, pointer=True,
                                          lhs=stencil_dofmap_name(arg),
                                          rhs=map_name + "%get_whole_dofmap()"))
                     # Add declaration and look-up of stencil size
                     parent.add(DeclGen(parent, datatype="integer",
                                        entity_decls=[stencil_size_name(arg)]))
                     parent.add(AssignGen(parent, lhs=stencil_size_name(arg),
                                          rhs=map_name + "%get_size()"))
def psyclone.dynamo0p3.DynInvokeStencil.unique_alg_vars (self)
returns a list of the names of the extent and direction arguments
specified in the algorithm layer
Definition at line 1540 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynInvokeStencil._unique_direction_vars(), and psyclone.dynamo0p3.DynInvokeStencil._unique_extent_vars().
     def unique_alg_vars(self):
         '''returns a list of the names of the extent and direction arguments
         specified in the algorithm layer'''
         return self._unique_extent_vars + self._unique_direction_vars
The documentation for this class was generated from the following file:
src/psyclone/dynamo0p3.py