PSyclone: psyclone.dynamo0p3.HaloDepth Class Reference
psyclone.dynamo0p3.HaloDepth Class Reference
Public Member Functions
def __init__ (self)
def annexed_only (self)
def max_depth (self)
def max_depth_m1 (self)
def var_depth (self)
def literal_depth (self)
def literal_depth (self, value)
def set_by_value (self, max_depth, var_depth, literal_depth, annexed_only, max_depth_m1)
def __str__ (self)
Detailed Description
Determines how much of the halo a read to a field accesses (the
halo depth)
Definition at line 4043 of file dynamo0p3.py.
Member Function Documentation
def psyclone.dynamo0p3.HaloDepth.__str__ (self)
return the depth of a halo dependency
as a string
Definition at line 4170 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth.literal_depth(), psyclone.dynamo0p3.HaloDepth.max_depth(), psyclone.dynamo0p3.HaloDepth.max_depth_m1(), and psyclone.dynamo0p3.HaloDepth.var_depth().
     def __str__(self):
         '''return the depth of a halo dependency
         as a string'''
         depth_str = ""
         if self.max_depth:
             depth_str += "mesh%get_halo_depth()"
         elif self.max_depth_m1:
             depth_str += "mesh%get_halo_depth()-1"
         else:
             if self.var_depth:
                 depth_str += self.var_depth
                 if self.literal_depth:
                     depth_str += "+"
             if self.literal_depth:
                 depth_str += str(self.literal_depth)
         return depth_str
def psyclone.dynamo0p3.HaloDepth.annexed_only (self)
Returns whether the access to the halo is solely to annexed dofs,
or not
:return: Return True if only annexed dofs are accessed in the
halo and False otherwise
:rtype: bool
Definition at line 4074 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._annexed_only.
     def annexed_only(self):
         '''Returns whether the access to the halo is solely to annexed dofs,
         or not
         :return: Return True if only annexed dofs are accessed in the
         halo and False otherwise
         :rtype: bool
         '''
         return self._annexed_only
def psyclone.dynamo0p3.HaloDepth.literal_depth (self)
Returns the known fixed (literal) depth of halo access. Note, this
depth should be added to the var_depth to find the total
depth.
:return: Return the known fixed (literal) halo
access depth
:rtype: integer
Definition at line 4124 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._literal_depth.
     def literal_depth(self):
         '''Returns the known fixed (literal) depth of halo access. Note, this
         depth should be added to the var_depth to find the total
         depth.
         :return: Return the known fixed (literal) halo
         access depth
         :rtype: integer
         '''
         return self._literal_depth
def psyclone.dynamo0p3.HaloDepth.literal_depth (self, value)
Set the known fixed (literal) depth of halo access.
:parameter value: Set the known fixed (literal) halo
access depth
:type value: integer
Definition at line 4137 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._literal_depth, psyclone.dynamo0p3.HaloDepth.literal_depth(), and psyclone.dynamo0p3.HaloDepth.set_by_value().
     def literal_depth(self, value):
         ''' Set the known fixed (literal) depth of halo access.
         :parameter value: Set the known fixed (literal) halo
         access depth
         :type value: integer
         '''
         self._literal_depth = value
def psyclone.dynamo0p3.HaloDepth.max_depth (self)
Returns whether the read to the field is known to access all of the
halo or not
:return: Return True if the read to the field is known to
access all of the halo and False otherwise
:rtype: bool
Definition at line 4086 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._max_depth.
     def max_depth(self):
         '''Returns whether the read to the field is known to access all of the
         halo or not
         :return: Return True if the read to the field is known to
         access all of the halo and False otherwise
         :rtype: bool
         '''
         return self._max_depth
def psyclone.dynamo0p3.HaloDepth.max_depth_m1 (self)
Returns whether the read to the field is known to access all of the
halo except the outermost level or not.
:return: Return True if the read to the field is known to
access all of the halo except the outermost and False otherwise
:rtype: bool
Definition at line 4098 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._max_depth_m1.
     def max_depth_m1(self):
         '''Returns whether the read to the field is known to access all of the
         halo except the outermost level or not.
         :return: Return True if the read to the field is known to
         access all of the halo except the outermost and False otherwise
         :rtype: bool
         '''
         return self._max_depth_m1
def psyclone.dynamo0p3.HaloDepth.set_by_value (self, max_depth, var_depth, literal_depth, annexed_only, max_depth_m1)
Set halo depth information directly
:param bool max_depth: True if the field accesses all of the \
halo and False otherwise
:param str var_depth: A variable name specifying the halo \
access depth, if one exists, and None if not
:param int literal_depth: The known fixed (literal) halo \
access depth
:param bool annexed_only: True if only the halo's annexed dofs \
are accessed and False otherwise
:param bool max_depth_m1: True if the field accesses all of \
the halo but does not require the outermost halo to be correct \
and False otherwise
Definition at line 4148 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._annexed_only, psyclone.dynamo0p3.HaloDepth._literal_depth, psyclone.dynamo0p3.HaloDepth._max_depth, psyclone.dynamo0p3.HaloDepth._max_depth_m1, and psyclone.dynamo0p3.HaloDepth._var_depth.
                      max_depth_m1):
         '''Set halo depth information directly
         :param bool max_depth: True if the field accesses all of the \
         halo and False otherwise
         :param str var_depth: A variable name specifying the halo \
         access depth, if one exists, and None if not
         :param int literal_depth: The known fixed (literal) halo \
         access depth
         :param bool annexed_only: True if only the halo's annexed dofs \
         are accessed and False otherwise
         :param bool max_depth_m1: True if the field accesses all of \
         the halo but does not require the outermost halo to be correct \
         and False otherwise
         '''
         self._max_depth = max_depth
         self._var_depth = var_depth
         self._literal_depth = literal_depth
         self._annexed_only = annexed_only
         self._max_depth_m1 = max_depth_m1
def psyclone.dynamo0p3.HaloDepth.var_depth (self)
Returns the name of the variable specifying the depth of halo
access if one is provided. Note, a variable will only be provided for
stencil accesses. Also note, this depth should be added to the
literal_depth to find the total depth.
:return: Return a variable name specifying the halo
access depth, if one exists, and None if not
:rtype: String
Definition at line 4110 of file dynamo0p3.py.
References psyclone.dynamo0p3.HaloDepth._var_depth.
     def var_depth(self):
         '''Returns the name of the variable specifying the depth of halo
         access if one is provided. Note, a variable will only be provided for
         stencil accesses. Also note, this depth should be added to the
         literal_depth to find the total depth.
         :return: Return a variable name specifying the halo
         access depth, if one exists, and None if not
         :rtype: String
         '''
         return self._var_depth
The documentation for this class was generated from the following file:
src/psyclone/dynamo0p3.py