PSyclone: psyclone.dynamo0p3.KernCallArgList Class Reference
psyclone.dynamo0p3.KernCallArgList Class Reference
Public Member Functions
def __init__ (self, kern, parent=None)
def cell_position (self)
def cell_map (self)
def mesh_height (self)
def mesh_ncell2d (self)
def field_vector (self, argvect)
def field (self, arg)
def stencil_unknown_extent (self, arg)
def stencil_unknown_direction (self, arg)
def stencil (self, arg)
def operator (self, arg)
def cma_operator (self, arg)
def scalar (self, scalar_arg)
def fs_common (self, function_space)
def fs_compulsory_field (self, function_space)
def fs_intergrid (self, function_space)
def basis (self, function_space)
def diff_basis (self, function_space)
def orientation (self, function_space)
def field_bcs_kernel (self, function_space)
def operator_bcs_kernel (self, function_space)
def quad_rule (self)
def banded_dofmap (self, function_space)
def indirection_dofmap (self, function_space, operator=None)
def arglist (self)
Public Member Functions inherited from psyclone.dynamo0p3.ArgOrdering
def __init__ (self, kern)
def generate (self)
def cell_position (self)
def cell_map (self)
def mesh_height (self)
def mesh_ncell2d (self)
def cma_operator (self, arg)
def field_vector (self, arg)
def field (self, arg)
def stencil_unknown_extent (self, arg)
def stencil_unknown_direction (self, arg)
def stencil (self, arg)
def operator (self, arg)
def scalar (self, arg)
def fs_common (self, function_space)
def fs_compulsory_field (self, function_space)
def basis (self, function_space)
def diff_basis (self, function_space)
def orientation (self, function_space)
def field_bcs_kernel (self, function_space)
def operator_bcs_kernel (self, function_space)
def quad_rule (self)
def banded_dofmap (self, function_space)
def indirection_dofmap (self, arg, operator=None)
Detailed Description
Creates the argument list required to call kernel "kern" from the
PSy-layer. The ordering and type of arguments is captured by the base
class.
:param kern: The kernel that is being called.
:type kern: :py:class:`psyclone.dynamo0p3.DynKern`
:param parent: parent of this kernel-call node in the PSyIRe.
:type parent: :py:class:`psyclone.f2pygen.DoGen`
Definition at line 5984 of file dynamo0p3.py.
Member Function Documentation
def psyclone.dynamo0p3.KernCallArgList.arglist (self)
:return: the kernel argument list. The generate function must be \
 called first.
:rtype: list of str.
:raises GenerationError: if the argument list is empty.
Definition at line 6274 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._arglist.
     def arglist(self):
         '''
         :return: the kernel argument list. The generate function must be \
                  called first.
         :rtype: list of str.
         :raises GenerationError: if the argument list is empty.
         '''
         if not self._arglist:
             raise GenerationError(
                 "Internal error. The argument list in KernCallArgList:"
                 "arglist() is empty. Has the generate() method been called?")
         return self._arglist
def psyclone.dynamo0p3.KernCallArgList.banded_dofmap (self, function_space)
Add banded dofmap (required for CMA operator assembly)
Definition at line 6262 of file dynamo0p3.py.
     def banded_dofmap(self, function_space):
         ''' Add banded dofmap (required for CMA operator assembly) '''
         # Note that the necessary ndf values will already have been added
         # to the argument list as they are mandatory for every function
         # space that appears in the meta-data.
         self._arglist.append(get_cbanded_map_name(function_space))
def psyclone.dynamo0p3.KernCallArgList.basis (self, function_space)
Add basis function information for this function space to the
argument list.
:param function_space: the function space for which the basis \
               function is required.
:type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
Definition at line 6155 of file dynamo0p3.py.
     def basis(self, function_space):
         '''
         Add basis function information for this function space to the
         argument list.
         :param function_space: the function space for which the basis \
                                function is required.
         :type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
         '''
         if self._kern.qr_required:
             basis_name = get_fs_basis_name(function_space,
                                            qr_var=self._kern.qr_name)
             self._arglist.append(basis_name)
         else:
             # We are dealing with an evaluator and therefore need as many
             # basis functions as there are target function spaces.
             for fs_name in self._kern.eval_targets:
                 # The associated FunctionSpace object is the first item in
                 # the tuple dict entry associated with the name of the target
                 # function space
                 fspace = self._kern.eval_targets[fs_name][0]
                 basis_name = get_fs_basis_name(function_space,
                                                qr_var=self._kern.qr_name,
                                                on_space=fspace)
                 self._arglist.append(basis_name)
def psyclone.dynamo0p3.KernCallArgList.cell_map (self)
Add cell-map and related cell counts to the argument list
Definition at line 6005 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._cell_ref_name().
     def cell_map(self):
         ''' Add cell-map and related cell counts to the argument list '''
         cargs = psyGen.args_filter(self._kern.args,
                                    arg_meshes=["gh_coarse"])
         carg = cargs[0]
         fargs = psyGen.args_filter(self._kern.args,
                                    arg_meshes=["gh_fine"])
         farg = fargs[0]
         base_name = "cell_map_" + carg.name
         map_name = self._name_space_manager.create_name(
             root_name=base_name, context="PSyVars", label=base_name)
         # Add the cell map to our argument list
         self._arglist.append("{0}(:,{1})".format(map_name,
                                                  self._cell_ref_name))
         # No. of fine cells per coarse cell
         base_name = "ncpc_{0}_{1}".format(farg.name, carg.name)
         ncellpercell = self._name_space_manager.create_name(
             root_name=base_name, context="PSyVars", label=base_name)
         self._arglist.append(ncellpercell)
         # No. of columns in the fine mesh
         base_name = "ncell_{0}".format(farg.name)
         ncell_fine = self._name_space_manager.create_name(
             root_name=base_name, context="PSyVars", label=base_name)
         self._arglist.append(ncell_fine)
def psyclone.dynamo0p3.KernCallArgList.cell_position (self)
add a cell argument to the argument list
Definition at line 6001 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._cell_ref_name().
     def cell_position(self):
         ''' add a cell argument to the argument list'''
         self._arglist.append(self._cell_ref_name)
def psyclone.dynamo0p3.KernCallArgList.cma_operator (self, arg)
add the CMA operator and associated scalars to the argument
list
Definition at line 6097 of file dynamo0p3.py.
     def cma_operator(self, arg):
         ''' add the CMA operator and associated scalars to the argument
         list '''
         if arg.function_space_to.orig_name != \
            arg.function_space_from.orig_name:
             components = ["matrix"] + DynInvokeCMAOperators.cma_diff_fs_params
         else:
             components = ["matrix"] + DynInvokeCMAOperators.cma_same_fs_params
         for component in components:
             self._arglist.append(
                 self._name_space_manager.create_name(
                     root_name=arg.name+"_"+component,
                     context="PSyVars",
                     label=arg.name+"_"+component))
def psyclone.dynamo0p3.KernCallArgList.diff_basis (self, function_space)
Add differential basis information for the function space to the
argument list.
:param function_space: the function space for which the differential
               basis functions are required
:type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
Definition at line 6181 of file dynamo0p3.py.
     def diff_basis(self, function_space):
         '''
         Add differential basis information for the function space to the
         argument list.
         :param function_space: the function space for which the differential
                                basis functions are required
         :type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
         '''
         if self._kern.qr_required:
             diff_basis_name = get_fs_diff_basis_name(
                 function_space, qr_var=self._kern.qr_name)
             self._arglist.append(diff_basis_name)
         else:
             # We are dealing with an evaluator and therefore need as many
             # basis functions as there are target function spaces.
             for fs_name in self._kern.eval_targets:
                 # The associated FunctionSpace object is the first item in
                 # the tuple dict entry associated with the name of the target
                 # function space
                 fspace = self._kern.eval_targets[fs_name][0]
                 diff_basis_name = get_fs_diff_basis_name(
                     function_space, qr_var=self._kern.qr_name, on_space=fspace)
                 self._arglist.append(diff_basis_name)
def psyclone.dynamo0p3.KernCallArgList.field (self, arg)
add the field array associated with the argument 'arg' to the
argument list
Definition at line 6061 of file dynamo0p3.py.
     def field(self, arg):
         '''add the field array associated with the argument 'arg' to the
         argument list'''
         text = arg.proxy_name + "%data"
         self._arglist.append(text)
def psyclone.dynamo0p3.KernCallArgList.field_bcs_kernel (self, function_space)
implement the boundary_dofs array fix for a field
Definition at line 6212 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._parent.
     def field_bcs_kernel(self, function_space):
         ''' implement the boundary_dofs array fix for a field '''
         from psyclone.f2pygen import DeclGen, AssignGen
         self._arglist.append("boundary_dofs")
         parent = self._parent
         parent.add(DeclGen(parent, datatype="integer",
                            pointer=True, entity_decls=[
                                "boundary_dofs(:,:) => null()"]))
         fspace = None
         for fspace in self._kern.arguments.unique_fss:
             if fspace.orig_name == "any_space_1":
                 break
         farg = self._kern.arguments.get_arg_on_space(fspace)
         # Sanity check - expect the enforce_bc_code kernel to only have
         # a field argument.
         if farg.type != "gh_field":
             raise GenerationError(
                 "Expected a gh_field from which to look-up boundary dofs "
                 "for kernel {0} but got {1}".format(self._kern.name,
                                                     farg.type))
         new_parent, position = parent.start_parent_loop()
         new_parent.add(AssignGen(new_parent, pointer=True,
                                  lhs="boundary_dofs",
                                  rhs=farg.proxy_name +
                                  "%vspace%get_boundary_dofs()"),
                        position=["before", position])
def psyclone.dynamo0p3.KernCallArgList.field_vector (self, argvect)
add the field vector associated with the argument 'argvect' to the
argument list
Definition at line 6051 of file dynamo0p3.py.
     def field_vector(self, argvect):
         '''add the field vector associated with the argument 'argvect' to the
         argument list '''
         # the range function below returns values from
         # 1 to the vector size which is what we
         # require in our Fortran code
         for idx in range(1, argvect.vector_size+1):
             text = argvect.proxy_name + "(" + str(idx) + ")%data"
             self._arglist.append(text)
def psyclone.dynamo0p3.KernCallArgList.fs_common (self, function_space)
add function-space related arguments common to LMA operators and
fields
Definition at line 6117 of file dynamo0p3.py.
     def fs_common(self, function_space):
         '''add function-space related arguments common to LMA operators and
         fields'''
         # There is currently one argument: "ndf"
         ndf_name = get_fs_ndf_name(function_space)
         self._arglist.append(ndf_name)
def psyclone.dynamo0p3.KernCallArgList.fs_compulsory_field (self, function_space)
add compulsory arguments to the argument list, when there is a
field on this function space
Definition at line 6124 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._cell_ref_name().
     def fs_compulsory_field(self, function_space):
         '''add compulsory arguments to the argument list, when there is a
         field on this function space'''
         undf_name = get_fs_undf_name(function_space)
         self._arglist.append(undf_name)
         map_name = get_fs_map_name(function_space)
         self._arglist.append(map_name+"(:,"+self._cell_ref_name+")")
def psyclone.dynamo0p3.KernCallArgList.fs_intergrid (self, function_space)
Add function-space related arguments for an intergrid kernel
:param function_space: the function space for which to add arguments
:type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
Definition at line 6132 of file dynamo0p3.py.
References psyclone.dynamo0p3.ArgOrdering.fs_common(), and psyclone.dynamo0p3.ArgOrdering.fs_compulsory_field().
     def fs_intergrid(self, function_space):
         '''
         Add function-space related arguments for an intergrid kernel
         :param function_space: the function space for which to add arguments
         :type function_space: :py:class:`psyclone.dynamo0p3.FunctionSpace`
         '''
         # Is this FS associated with the coarse or fine mesh? (All fields
         # on a given mesh must be on the same FS.)
         arg = self._kern.arguments.get_arg_on_space(function_space)
         if arg.mesh == "gh_fine":
             # For the fine mesh, we need ndf, undf and the *whole*
             # dofmap
             self.fs_common(function_space)
             undf_name = get_fs_undf_name(function_space)
             self._arglist.append(undf_name)
             map_name = get_fs_map_name(function_space)
             self._arglist.append(map_name)
         else:
             # For the coarse mesh we only need undf and the dofmap for
             # the current column
             self.fs_compulsory_field(function_space)
def psyclone.dynamo0p3.KernCallArgList.indirection_dofmap (self, function_space, operator = None)
Add indirection dofmap required when applying a CMA operator
Definition at line 6269 of file dynamo0p3.py.
     def indirection_dofmap(self, function_space, operator=None):
         ''' Add indirection dofmap required when applying a CMA operator '''
         self._arglist.append(get_cma_indirection_map_name(function_space))
def psyclone.dynamo0p3.KernCallArgList.mesh_height (self)
add mesh height (nlayers) to the argument list
Definition at line 6030 of file dynamo0p3.py.
     def mesh_height(self):
         ''' add mesh height (nlayers) to the argument list'''
         nlayers_name = self._name_space_manager.create_name(
             root_name="nlayers", context="PSyVars", label="nlayers")
         self._arglist.append(nlayers_name)
def psyclone.dynamo0p3.KernCallArgList.mesh_ncell2d (self)
Add the number of columns in the mesh to the argument list
Definition at line 6045 of file dynamo0p3.py.
     def mesh_ncell2d(self):
         ''' Add the number of columns in the mesh to the argument list '''
         ncell2d_name = self._name_space_manager.create_name(
             root_name="ncell_2d", context="PSyVars", label="ncell_2d")
         self._arglist.append(ncell2d_name)
def psyclone.dynamo0p3.KernCallArgList.operator (self, arg)
add the operator arguments to the argument list
Definition at line 6090 of file dynamo0p3.py.
     def operator(self, arg):
         ''' add the operator arguments to the argument list '''
         # TODO we should only be including ncell_3d once in the argument
         # list but this adds it for every operator
         self._arglist.append(arg.proxy_name_indexed+"%ncell_3d")
         self._arglist.append(arg.proxy_name_indexed+"%local_stencil")
def psyclone.dynamo0p3.KernCallArgList.operator_bcs_kernel (self, function_space)
Supply necessary additional arguments for the kernel that
applies boundary conditions to a LMA operator
Definition at line 6239 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._parent.
     def operator_bcs_kernel(self, function_space):
         ''' Supply necessary additional arguments for the kernel that
         applies boundary conditions to a LMA operator '''
         from psyclone.f2pygen import DeclGen, AssignGen
         # This kernel has only a single LMA operator as argument.
         # Checks for this are performed in ArgOrdering.generate()
         op_arg = self._kern.arguments.args[0]
         self._arglist.append("boundary_dofs")
         parent = self._parent
         parent.add(DeclGen(parent, datatype="integer",
                            pointer=True, entity_decls=[
                                "boundary_dofs(:,:) => null()"]))
         new_parent, position = parent.start_parent_loop()
         new_parent.add(AssignGen(new_parent, pointer=True,
                                  lhs="boundary_dofs",
                                  rhs=op_arg.proxy_name +
                                  "%fs_to%get_boundary_dofs()"),
                        position=["before", position])
def psyclone.dynamo0p3.KernCallArgList.orientation (self, function_space)
add orientation information for this function space to the
argument list
Definition at line 6206 of file dynamo0p3.py.
     def orientation(self, function_space):
         '''add orientation information for this function space to the
         argument list'''
         orientation_name = get_fs_orientation_name(function_space)
         self._arglist.append(orientation_name)
def psyclone.dynamo0p3.KernCallArgList.quad_rule (self)
add qr information to the argument list
Definition at line 6258 of file dynamo0p3.py.
     def quad_rule(self):
         ''' add qr information to the argument list'''
         self._arglist.extend(self._kern.qr_args)
def psyclone.dynamo0p3.KernCallArgList.scalar (self, scalar_arg)
add the name associated with the scalar argument to the argument
list
Definition at line 6112 of file dynamo0p3.py.
     def scalar(self, scalar_arg):
         '''add the name associated with the scalar argument to the argument
         list'''
         self._arglist.append(scalar_arg.name)
def psyclone.dynamo0p3.KernCallArgList.stencil (self, arg)
add general stencil information associated with the argument 'arg'
to the argument list
Definition at line 6082 of file dynamo0p3.py.
References psyclone.dynamo0p3.KernCallArgList._cell_ref_name().
     def stencil(self, arg):
         '''add general stencil information associated with the argument 'arg'
         to the argument list'''
         # add in stencil dofmap
         var_name = stencil_dofmap_name(arg)
         name = var_name + "(:,:," + self._cell_ref_name + ")"
         self._arglist.append(name)
def psyclone.dynamo0p3.KernCallArgList.stencil_unknown_direction (self, arg)
add stencil information to the argument list associated with the
argument 'arg' if the direction is unknown
Definition at line 6075 of file dynamo0p3.py.
     def stencil_unknown_direction(self, arg):
         '''add stencil information to the argument list associated with the
         argument 'arg' if the direction is unknown'''
         # the direction of the stencil is not known so pass the value in
         name = arg.stencil.direction_arg.varName
         self._arglist.append(name)
def psyclone.dynamo0p3.KernCallArgList.stencil_unknown_extent (self, arg)
add stencil information to the argument list associated with the
argument 'arg' if the extent is unknown
Definition at line 6067 of file dynamo0p3.py.
     def stencil_unknown_extent(self, arg):
         '''add stencil information to the argument list associated with the
         argument 'arg' if the extent is unknown'''
         # the extent is not specified in the metadata
         # so pass the value in
         name = stencil_size_name(arg)
         self._arglist.append(name)
The documentation for this class was generated from the following file:
src/psyclone/dynamo0p3.py