PSyclone: psyclone.configuration.Config Class Reference
psyclone.configuration.Config Class Reference
Public Member Functions
def __init__ (self)
def load (self, config_file=None)
def api_conf (self, api)
def distributed_memory (self)
def distributed_memory (self, dist_mem)
def default_api (self)
def api (self)
def api (self, api)
def supported_apis (self)
def default_stub_api (self)
def supported_stub_apis (self)
def reproducible_reductions (self)
def reprod_pad_size (self)
def filename (self)
def kernel_output_dir (self)
def kernel_output_dir (self, value)
def kernel_naming (self)
def kernel_naming (self, value)
def include_paths (self)
def include_paths (self, path_list)
def get_default_keys (self)
Static Public Member Functions
def get (do_not_load_file=False)
def find_file ()
Detailed Description
Handles all configuration management. It is implemented as a singleton
using a class _instance variable and a get() function.
Definition at line 78 of file configuration.py.
Constructor & Destructor Documentation
def psyclone.configuration.Config.__init__ (self)
This is the basic constructor that only sets the supported APIs
and stub APIs, it does not load a config file. The Config instance
is a singleton, and as such will test that no instance already exists
and raise an exception otherwise.
:raises GenerationError: If a singleton instance of Config already \
exists.
Definition at line 125 of file configuration.py.
References psyclone.configuration.Config._api, psyclone.configuration.Config._api_conf, psyclone.configuration.Config._config, psyclone.configuration.Config._config_file, psyclone.configuration.Config._default_stub_api, psyclone.configuration.Config._distributed_mem, psyclone.configuration.Config._include_paths, psyclone.configuration.Config._kernel_naming, psyclone.configuration.Config._kernel_output_dir, psyclone.configuration.Config._reprod_pad_size, and psyclone.configuration.Config._reproducible_reductions.
     def __init__(self):
         '''This is the basic constructor that only sets the supported APIs
         and stub APIs, it does not load a config file. The Config instance
         is a singleton, and as such will test that no instance already exists
         and raise an exception otherwise.
         :raises GenerationError: If a singleton instance of Config already \
                 exists.
         '''
         if Config._instance is not None:
             raise ConfigurationError("Only one instance of "
                                      "Config can be created")
         # This dictionary stores the API-specific config instances
         # for each API specified in a config file.
         self._api_conf = {}
         # This will store the ConfigParser instance for the specified
         # config file.
         self._config = None
         # The name (including path) of the config file read.
         self._config_file = None
         # The API selected by the user - either on the command line,
         # or in the config file (or the default if neither).
         self._api = None
         # The default stub API to use.
         self._default_stub_api = None
         # True if distributed memory code should be created/
         self._distributed_mem = None
         # True if reproducible reductions should be used.
         self._reproducible_reductions = None
         # Padding size (number of array elements) to be used when
         # reproducible reductions are created.
         self._reprod_pad_size = None
         # Where to write transformed kernels - set at runtime
         self._kernel_output_dir = None
         # The naming scheme to use for transformed kernels
         self._kernel_naming = None
         # The list of directories to search for Fortran include files
         self._include_paths = []
Member Function Documentation
def psyclone.configuration.Config.api (self)
Getter for the API selected by the user.
:returns: The name of the selected API.
:rtype: str
Definition at line 411 of file configuration.py.
References psyclone.configuration.Config._api.
     def api(self):
         '''Getter for the API selected by the user.
         :returns: The name of the selected API.
         :rtype: str
         '''
         return self._api
def psyclone.configuration.Config.api (self, api)
Setter for the API selected by the user.
:param str api: The name of the API to use.
:raises ValueError if api is not a supported API.
Definition at line 420 of file configuration.py.
References psyclone.configuration.Config._api, psyclone.configuration.Config._supported_api_list, and psyclone.configuration.Config.api().
     def api(self, api):
         '''Setter for the API selected by the user.
         :param str api: The name of the API to use.
         :raises ValueError if api is not a supported API.
         '''
         if api not in self._supported_api_list:
             raise ValueError("'{0}' is not a valid API, it must be one "
                              "of {1}'.".format(api,
                                                Config._supported_api_list))
         self._api = api
def psyclone.configuration.Config.api_conf (self, api)
Getter for the object holding API-specific configuration options.
:param str api: the API for which configuration details are required.
:returns: object containing API-specific configuration
:rtype: One of :py:class:`psyclone.configuration.DynConfig`,
:py:class:`psyclone.configuration.GOceanConfig` or None.
:raises ConfigurationError: if api is not in the list of supported \
                    APIs.
:raises ConfigurationError: if the config file did not contain a \
                    section for the requested API.
Definition at line 301 of file configuration.py.
References psyclone.configuration.Config._api_conf, and psyclone.configuration.Config.supported_apis().
     def api_conf(self, api):
         '''
         Getter for the object holding API-specific configuration options.
         :param str api: the API for which configuration details are required.
         :returns: object containing API-specific configuration
         :rtype: One of :py:class:`psyclone.configuration.DynConfig`,
                 :py:class:`psyclone.configuration.GOceanConfig` or None.
         :raises ConfigurationError: if api is not in the list of supported \
                                     APIs.
         :raises ConfigurationError: if the config file did not contain a \
                                     section for the requested API.
         '''
         if api not in self.supported_apis:
             raise ConfigurationError(
                 "API '{0}' is not in the list '{1}'' of supported APIs."
                 .format(api, self.supported_apis))
         if api not in self._api_conf:
             raise ConfigurationError(
                 "Configuration file did not contain a section for the '{0}' "
                 "API".format(api), config=self)
         return self._api_conf[api]
def psyclone.configuration.Config.default_api (self)
Getter for the default API used by PSyclone.
:returns: default PSyclone API
:rtype: str
Definition at line 401 of file configuration.py.
References psyclone.configuration.Config._default_api.
     def default_api(self):
         '''
         Getter for the default API used by PSyclone.
         :returns: default PSyclone API
         :rtype: str
         '''
         return self._default_api
def psyclone.configuration.Config.default_stub_api (self)
Getter for the default API used by the stub generator.
:returns: default API for the stub generator
:rtype: str
Definition at line 444 of file configuration.py.
References psyclone.configuration.Config._default_stub_api.
     def default_stub_api(self):
         '''
         Getter for the default API used by the stub generator.
         :returns: default API for the stub generator
         :rtype: str
         '''
         return self._default_stub_api
def psyclone.configuration.Config.distributed_memory (self)
Getter for whether or not distributed memory is enabled
:returns: True if DM is enabled, False otherwise
:rtype: bool
Definition at line 377 of file configuration.py.
References psyclone.configuration.Config._distributed_mem.
     def distributed_memory(self):
         '''
         Getter for whether or not distributed memory is enabled
         :returns: True if DM is enabled, False otherwise
         :rtype: bool
         '''
         return self._distributed_mem
def psyclone.configuration.Config.distributed_memory (self, dist_mem)
Setter for whether or not distributed memory support is enabled
in this configuration.
:param bool dist_mem: Whether or not dm is enabled
Definition at line 387 of file configuration.py.
References psyclone.configuration.Config._distributed_mem, and psyclone.configuration.Config.distributed_memory().
     def distributed_memory(self, dist_mem):
         '''
         Setter for whether or not distributed memory support is enabled
         in this configuration.
         :param bool dist_mem: Whether or not dm is enabled
         '''
         if not isinstance(dist_mem, bool):
             raise ConfigurationError(
                 "distributed_memory must be a boolean but got {0}".
                 format(type(dist_mem)))
         self._distributed_mem = dist_mem
def psyclone.configuration.Config.filename (self)
Getter for the full path and name of the configuration file used
to initialise this configuration object.
:returns: full path and name of configuration file
:rtype: str
Definition at line 485 of file configuration.py.
References psyclone.configuration.Config._config_file.
     def filename(self):
         '''
         Getter for the full path and name of the configuration file used
         to initialise this configuration object.
         :returns: full path and name of configuration file
         :rtype: str
         '''
         return self._config_file
def psyclone.configuration.Config.find_file () static
Static method that searches various locations for a configuration
file. If the full path to an existing file has been provided in
the PSYCLONE_CONFIG environment variable then that is returned.
Otherwise, we search the following locations, in order:
- ${PWD}/.psyclone/
-  if inside-a-virtual-environment:
      <base-dir-of-virtual-env>/share/psyclone/
- ${HOME}/.local/share/psyclone/
- <system-install-prefix>/share/psyclone/
:returns: the fully-qualified path to the configuration file
:rtype: str
:raises ConfigurationError: if no config file is found
Definition at line 326 of file configuration.py.
     def find_file():
         '''
         Static method that searches various locations for a configuration
         file. If the full path to an existing file has been provided in
         the PSYCLONE_CONFIG environment variable then that is returned.
         Otherwise, we search the following locations, in order:
         - ${PWD}/.psyclone/
         -  if inside-a-virtual-environment:
               <base-dir-of-virtual-env>/share/psyclone/
         - ${HOME}/.local/share/psyclone/
         - <system-install-prefix>/share/psyclone/
         :returns: the fully-qualified path to the configuration file
         :rtype: str
         :raises ConfigurationError: if no config file is found
         '''
         import sys
         from psyclone.virtual_utils import within_virtual_env
         # If $PSYCLONE_CONFIG is set then we use that unless the
         # file it points to does not exist
         _psy_config = os.environ.get('PSYCLONE_CONFIG')
         if _psy_config and os.path.isfile(_psy_config):
             return _psy_config
         # Set up list of locations to search
         share_dir = os.path.join(sys.prefix, "share", "psyclone")
         # 1. .psyclone/ in the CWD
         _file_paths = [os.path.join(os.getcwd(), ".psyclone")]
         if within_virtual_env():
             # 2. <virtual-env-base>/share/psyclone/
             _file_paths.append(share_dir)
         # 3. ~/.local/share/psyclone/
         _file_paths.append(os.path.join(os.path.expanduser("~"),
                                         ".local", "share", "psyclone"))
         if not within_virtual_env():
             # 4. <python-installation-base>/share/psyclone/
             _file_paths.append(share_dir)
         for cfile in [os.path.join(cdir, _FILE_NAME) for cdir in _file_paths]:
             if os.path.isfile(cfile):
                 return cfile
         # If we get to here then we have failed to find a config file
         raise ConfigurationError("{0} not found in any of {1}".
                                  format(_FILE_NAME, _file_paths))
def psyclone.configuration.Config.get (do_not_load_file = False) static
Static function that if necessary creates and returns the singleton
config instance.
:param bool do_not_load_file: If set it will not load the default \
       config file. This is used when handling the command line so \
       that the user can specify the file to load.
Definition at line 110 of file configuration.py.
     def get(do_not_load_file=False):
         '''Static function that if necessary creates and returns the singleton
         config instance.
         :param bool do_not_load_file: If set it will not load the default \
                config file. This is used when handling the command line so \
                that the user can specify the file to load.
         '''
         if not Config._instance:
             Config._instance = Config()
             if not do_not_load_file:
                 Config._instance.load()
         return Config._instance
def psyclone.configuration.Config.get_default_keys (self)
Returns all keys from the default section.
:returns list: List of all keys of the default section as strings.
Definition at line 570 of file configuration.py.
     def get_default_keys(self):
         '''Returns all keys from the default section.
         :returns list: List of all keys of the default section as strings.
         '''
         return self._config.defaults()
def psyclone.configuration.Config.include_paths (self)
:returns: the list of paths to search for Fortran include files.
:rtype: list of str.
Definition at line 540 of file configuration.py.
References psyclone.configuration.Config._include_paths.
     def include_paths(self):
         '''
         :returns: the list of paths to search for Fortran include files.
         :rtype: list of str.
         '''
         return self._include_paths
def psyclone.configuration.Config.include_paths (self, path_list)
Sets the list of paths to search for Fortran include files.
:param path_list: list of directories to search.
:type path_list: list of str.
:raises ValueError: if `path_list` is not a list-like object.
:raises ConfigurationError: if any of the paths in the list do \
                    not exist.
Definition at line 548 of file configuration.py.
References psyclone.configuration.Config._include_paths, and psyclone.configuration.Config.include_paths().
     def include_paths(self, path_list):
         '''
         Sets the list of paths to search for Fortran include files.
         :param path_list: list of directories to search.
         :type path_list: list of str.
         :raises ValueError: if `path_list` is not a list-like object.
         :raises ConfigurationError: if any of the paths in the list do \
                                     not exist.
         '''
         self._include_paths = []
         try:
             for path in path_list:
                 if not os.path.exists(path):
                     raise ConfigurationError(
                         "Include path '{0}' does not exist".format(path))
                 self._include_paths.append(path)
         except (TypeError, ValueError):
             raise ValueError("include_paths must be a list but got: {0}".
                              format(type(path_list)))
def psyclone.configuration.Config.kernel_naming (self)
:returns: what naming scheme to use when writing transformed kernels \
  to file.
:rtype: str
Definition at line 515 of file configuration.py.
References psyclone.configuration.Config._kernel_naming.
     def kernel_naming(self):
         '''
         :returns: what naming scheme to use when writing transformed kernels \
                   to file.
         :rtype: str
         '''
         return self._kernel_naming
def psyclone.configuration.Config.kernel_naming (self, value)
Setter for how to re-name kernels when writing transformed kernels
to file.
:param str value: one of VALID_KERNEL_NAMING_SCHEMES.
:raises ValueError: if the supplied value is not a recognised \
            kernel-renaming scheme.
Definition at line 524 of file configuration.py.
References psyclone.configuration.Config._kernel_naming, and psyclone.configuration.Config.kernel_naming().
     def kernel_naming(self, value):
         '''
         Setter for how to re-name kernels when writing transformed kernels
         to file.
         :param str value: one of VALID_KERNEL_NAMING_SCHEMES.
         :raises ValueError: if the supplied value is not a recognised \
                             kernel-renaming scheme.
         '''
         if value not in VALID_KERNEL_NAMING_SCHEMES:
             raise ValueError(
                 "kernel_naming must be one of '{0}' but got '{1}'".
                 format(VALID_KERNEL_NAMING_SCHEMES, value))
         self._kernel_naming = value
def psyclone.configuration.Config.kernel_output_dir (self)
:returns: the directory to which to write transformed kernels.
:rtype: str
Definition at line 496 of file configuration.py.
References psyclone.configuration.Config._kernel_output_dir.
     def kernel_output_dir(self):
         '''
         :returns: the directory to which to write transformed kernels.
         :rtype: str
         '''
         if not self._kernel_output_dir:
             # We use the CWD if no directory has been specified
             self._kernel_output_dir = os.getcwd()
         return self._kernel_output_dir
def psyclone.configuration.Config.kernel_output_dir (self, value)
Setter for kernel output directory.
:param str value: directory to which to write transformed kernels.
Definition at line 507 of file configuration.py.
References psyclone.configuration.Config._kernel_output_dir, and psyclone.configuration.Config.kernel_output_dir().
     def kernel_output_dir(self, value):
         '''
         Setter for kernel output directory.
         :param str value: directory to which to write transformed kernels.
         '''
         self._kernel_output_dir = value
def psyclone.configuration.Config.load (self, config_file = None)
Loads a configuration file.
:param str config_file: Override default configuration file to read.
:raises ConfigurationError: if there are errors or inconsistencies in \
                the specified config file.
Definition at line 176 of file configuration.py.
References psyclone.configuration.Config._api, psyclone.configuration.Config._api_conf, psyclone.configuration.Config._config, psyclone.configuration.Config._config_file, psyclone.configuration.Config._default_stub_api, psyclone.configuration.Config._distributed_mem, psyclone.configuration.Config._kernel_naming, psyclone.configuration.Config._reprod_pad_size, and psyclone.configuration.Config._reproducible_reductions.
     def load(self, config_file=None):
         '''Loads a configuration file.
         :param str config_file: Override default configuration file to read.
         :raises ConfigurationError: if there are errors or inconsistencies in \
                                 the specified config file.
         '''
         # pylint: disable=too-many-branches, too-many-statements
         if config_file:
             # Caller has explicitly provided the full path to the config
             # file to read
             if not os.path.isfile(config_file):
                 raise ConfigurationError(
                     "File {0} does not exist".format(config_file))
             self._config_file = config_file[:]
         else:
             # Search for the config file in various default locations
             self._config_file = Config.find_file()
         from configparser import ConfigParser, MissingSectionHeaderError
         self._config = ConfigParser()
         try:
             self._config.read(self._config_file)
         except MissingSectionHeaderError as err:
             raise ConfigurationError(
                 "ConfigParser failed to read the configuration file. Is it "
                 "formatted correctly? (Error was: {0})".format(str(err)),
                 config=self)
         # Check that the configuration file has a [DEFAULT] section. Even
         # if there isn't one in the file, ConfigParser creates an (empty)
         # dictionary entry for it.
         if 'DEFAULT' not in self._config or \
            not self._config['DEFAULT'].keys():
             raise ConfigurationError(
                 "Configuration file has no [DEFAULT] section", config=self)
         # The call to the 'read' method above populates a dictionary.
         # All of the entries in that dict are unicode strings so here
         # we pull out the values we want and deal with any type
         # conversion. We protect each of these with a try block so as
         # to catch any conversion errors due to incorrect entries in
         # the config file.
         try:
             self._distributed_mem = self._config['DEFAULT'].getboolean(
                 'DISTRIBUTED_MEMORY')
         except ValueError as err:
             raise ConfigurationError(
                 "error while parsing DISTRIBUTED_MEMORY: {0}".
                 format(str(err)), config=self)
         # API for psyclone
         if "API" in self._config["DEFAULT"]:
             self._api = self._config['DEFAULT']['API']
         else:
             self._api = Config._default_api
             # Test if we have exactly one section (besides DEFAULT).
             # If so, make this section the API (otherwise stick with
             # the default API)
             if len(self._config) == 2:
                 for section in self._config:
                     self._api = section.lower()
                     if self._api != "default":
                         break
         # Sanity check
         if self._api not in Config._supported_api_list:
             raise ConfigurationError(
                 "The API ({0}) is not in the list of supported "
                 "APIs ({1}).".format(self._api,
                                      Config._supported_api_list),
                 config=self)
         # Default API for stub-generator
         if 'defaultstubapi' not in self._config['DEFAULT']:
             # Use the default API if no default is specified for stub API
             self._default_stub_api = Config._default_api
         else:
             self._default_stub_api = self._config['DEFAULT']['DEFAULTSTUBAPI']
         # Sanity check for defaultstubapi:
         if self._default_stub_api not in Config._supported_stub_api_list:
             raise ConfigurationError(
                 "The default stub API ({0}) is not in the list of "
                 "supported stub APIs ({1}).".format(
                     self._default_stub_api,
                     Config._supported_stub_api_list),
                 config=self)
         try:
             self._reproducible_reductions = self._config['DEFAULT'].getboolean(
                 'REPRODUCIBLE_REDUCTIONS')
         except ValueError as err:
             raise ConfigurationError(
                 "error while parsing REPRODUCIBLE_REDUCTIONS: {0}".
                 format(str(err)), config=self)
         try:
             self._reprod_pad_size = self._config['DEFAULT'].getint(
                 'REPROD_PAD_SIZE')
         except ValueError as err:
             raise ConfigurationError(
                 "error while parsing REPROD_PAD_SIZE: {0}".format(str(err)),
                 config=self)
         # Now we deal with the API-specific sections of the config file. We
         # create a dictionary to hold the API-specifc Config objects.
         self._api_conf = {}
         for api in Config._supported_api_list:
             if api in self._config:
                 if api == "dynamo0.3":
                     self._api_conf[api] = DynConfig(self, self._config[api])
                 elif api == "gocean1.0":
                     self._api_conf[api] = GOceanConfig(self, self._config[api])
                 else:
                     raise NotImplementedError(
                         "Configuration file contains a {0} section but no "
                         "Config sub-class has been implemented for this API".
                         format(api))
         # The scheme to use when re-naming transformed kernels.
         # By default we ensure that each transformed kernel is given a
         # unique name (within the specified kernel-output directory).
         self._kernel_naming = Config._default_kernel_naming
def psyclone.configuration.Config.reprod_pad_size (self)
Getter for the amount of padding to use for the array required
for reproducible OpenMP reductions
:returns: padding size (no. of array elements)
:rtype: int
Definition at line 474 of file configuration.py.
References psyclone.configuration.Config._reprod_pad_size.
     def reprod_pad_size(self):
         '''
         Getter for the amount of padding to use for the array required
         for reproducible OpenMP reductions
         :returns: padding size (no. of array elements)
         :rtype: int
         '''
         return self._reprod_pad_size
def psyclone.configuration.Config.reproducible_reductions (self)
Getter for whether reproducible reductions are enabled.
:returns: True if reproducible reductions are enabled, False otherwise.
:rtype: bool
Definition at line 464 of file configuration.py.
References psyclone.configuration.Config._reproducible_reductions.
     def reproducible_reductions(self):
         '''
         Getter for whether reproducible reductions are enabled.
         :returns: True if reproducible reductions are enabled, False otherwise.
         :rtype: bool
         '''
         return self._reproducible_reductions
def psyclone.configuration.Config.supported_apis (self)
Getter for the list of APIs supported by PSyclone.
:returns: list of supported APIs
:rtype: list of str
Definition at line 434 of file configuration.py.
     def supported_apis(self):
         '''
         Getter for the list of APIs supported by PSyclone.
         :returns: list of supported APIs
         :rtype: list of str
         '''
         return Config._supported_api_list
def psyclone.configuration.Config.supported_stub_apis (self)
Getter for the list of APIs supported by the stub generator.
:returns: list of supported APIs.
:rtype: list of str
Definition at line 454 of file configuration.py.
     def supported_stub_apis(self):
         '''
         Getter for the list of APIs supported by the stub generator.
         :returns: list of supported APIs.
         :rtype: list of str
         '''
         return Config._supported_stub_api_list
The documentation for this class was generated from the following file:
src/psyclone/configuration.py