PSyclone: psyclone.dynamo0p3.DynArgDescriptor03 Class Reference
psyclone.dynamo0p3.DynArgDescriptor03 Class Reference
Public Member Functions
def __init__ (self, arg_type)
def function_space_to (self)
def function_space_from (self)
def function_space (self)
def function_spaces (self)
def vector_size (self)
def type (self)
def __str__ (self)
def __repr__ (self)
Public Member Functions inherited from psyclone.parse.Descriptor
def __init__ (self, access, space, stencil=None, mesh=None)
def access (self)
def function_space (self)
def stencil (self)
def mesh (self)
def __repr__ (self)
Detailed Description
This class captures the information specified in an argument
descriptor.
Definition at line 519 of file dynamo0p3.py.
Constructor & Destructor Documentation
def psyclone.dynamo0p3.DynArgDescriptor03.__init__ (self, arg_type)
:param arg_type: dynamo0.3 argument type (scalar, field or operator)
:type arg_type: :py:class:`psyclone.dynamo0p3.DynKernelArgument`
Definition at line 523 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._access_descriptor, psyclone.dynamo0p3.DynArgDescriptor03._arg_type, psyclone.dynamo0p3.DynArgDescriptor03._function_space1, psyclone.dynamo0p3.DynArgDescriptor03._function_space2, psyclone.dynamo0p3.DynArgDescriptor03._type, and psyclone.dynamo0p3.DynArgDescriptor03._vector_size.
     def __init__(self, arg_type):
         '''
         :param arg_type: dynamo0.3 argument type (scalar, field or operator)
         :type arg_type: :py:class:`psyclone.dynamo0p3.DynKernelArgument`
         '''
         self._arg_type = arg_type
         if arg_type.name != 'arg_type':
             raise ParseError(
                 "In the dynamo0.3 API each meta_arg entry must be of type "
                 "'arg_type', but found '{0}'".format(arg_type.name))
         # We require at least 2 args
         if len(arg_type.args) < 2:
             raise ParseError(
                 "In the dynamo0.3 API each meta_arg entry must have at least "
                 "2 args, but found '{0}'".format(len(arg_type.args)))
         # The first arg is the type of field, possibly with a *n appended
         self._vector_size = 1
         if isinstance(arg_type.args[0], expr.BinaryOperator):
             # We expect 'field_type * n' to have been specified
             self._type = arg_type.args[0].toks[0].name
             operator = arg_type.args[0].toks[1]
             try:
                 self._vector_size = int(arg_type.args[0].toks[2])
             except TypeError:
                 raise ParseError(
                     "In the dynamo0.3 API vector notation expects the format "
                     "(field*n) where n is an integer, but the following was "
                     "found '{0}' in '{1}'.".
                     format(str(arg_type.args[0].toks[2]), arg_type))
             if self._type not in VALID_ARG_TYPE_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API the 1st argument of a meta_arg "
                     "entry should be a valid argument type (one of {0}), but "
                     "found '{1}' in '{2}'".format(VALID_ARG_TYPE_NAMES,
                                                   self._type, arg_type))
             if self._type in VALID_SCALAR_NAMES and self._vector_size > 1:
                 raise ParseError(
                     "In the dynamo0.3 API vector notation is not supported "
                     "for scalar arguments (found '{0}')".
                     format(arg_type.args[0]))
             if operator != "*":
                 raise ParseError(
                     "In the dynamo0.3 API the 1st argument of a meta_arg "
                     "entry may be a vector but if so must use '*' as the "
                     "separator in the format (field*n), but found '{0}' in "
                     "'{1}'".format(operator, arg_type))
             if self._vector_size <= 1:
                 raise ParseError(
                     "In the dynamo0.3 API the 1st argument of a meta_arg "
                     "entry may be a vector but if so must contain a valid "
                     "integer vector size in the format (field*n where n>1), "
                     "but found '{0}' in '{1}'".format(self._vector_size,
                                                       arg_type))
         elif isinstance(arg_type.args[0], expr.FunctionVar):
             # We expect 'field_type' to have been specified
             if arg_type.args[0].name not in VALID_ARG_TYPE_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API the 1st argument of a "
                     "meta_arg entry should be a valid argument type (one of "
                     "{0}), but found '{1}' in '{2}'".
                     format(VALID_ARG_TYPE_NAMES, arg_type.args[0].name,
                            arg_type))
             self._type = arg_type.args[0].name
         else:
             raise ParseError(
                 "Internal error in DynArgDescriptor03.__init__, (1) should "
                 "not get to here")
         # The 2nd arg is an access descriptor
         if arg_type.args[1].name not in VALID_ACCESS_DESCRIPTOR_NAMES:
             raise ParseError(
                 "In the dynamo0.3 API the 2nd argument of a meta_arg entry "
                 "must be a valid access descriptor (one of {0}), but found "
                 "'{1}' in '{2}'".format(VALID_ACCESS_DESCRIPTOR_NAMES,
                                         arg_type.args[1].name, arg_type))
         self._access_descriptor = arg_type.args[1]
         # Reduction access descriptors are only valid for real scalar arguments
         if self._type != "gh_real" and \
            self._access_descriptor.name in VALID_REDUCTION_NAMES:
             raise ParseError(
                 "In the dynamo0.3 API a reduction access '{0}' is only valid "
                 "with a real scalar argument, but '{1}' was found".
                 format(self._access_descriptor.name, self._type))
         # FIELD, OPERATOR and SCALAR datatypes descriptors and rules
         stencil = None
         mesh = None
         # Fields
         if self._type == "gh_field":
             if len(arg_type.args) < 3:
                 raise ParseError(
                     "In the dynamo0.3 API each meta_arg entry must have at "
                     "least 3 arguments if its first argument is gh_field, but "
                     "found {0} in '{1}'".format(len(arg_type.args), arg_type)
                     )
             # There must be at most 4 arguments.
             if len(arg_type.args) > 4:
                 raise ParseError(
                     "In the dynamo0.3 API each meta_arg entry must have at "
                     "most 4 arguments if its first argument is gh_field, but "
                     "found {0} in '{1}'".format(len(arg_type.args), arg_type))
             # The 3rd argument must be a function space name
             if arg_type.args[2].name not in VALID_FUNCTION_SPACE_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API the 3rd argument of a meta_arg "
                     "entry must be a valid function space name if its first "
                     "argument is gh_field (one of {0}), but found '{1}' in "
                     "'{2}".format(VALID_FUNCTION_SPACE_NAMES,
                                   arg_type.args[2].name, arg_type))
             self._function_space1 = arg_type.args[2].name
             # The optional 4th argument is either a stencil specification
             # or a mesh identifier (for inter-grid kernels)
             if len(arg_type.args) == 4:
                 try:
                     from psyclone.parse import get_stencil, get_mesh
                     if "stencil" in str(arg_type.args[3]):
                         stencil = get_stencil(arg_type.args[3],
                                               VALID_STENCIL_TYPES)
                     elif "mesh" in str(arg_type.args[3]):
                         mesh = get_mesh(arg_type.args[3], VALID_MESH_TYPES)
                     else:
                         raise ParseError("Unrecognised meta-data entry")
                 except ParseError as err:
                     raise ParseError(
                         "In the dynamo0.3 API the 4th argument of a "
                         "meta_arg entry must be either a valid stencil "
                         "specification  or a mesh identifier (for inter-"
                         "grid kernels). However, "
                         "entry {0} raised the following error: {1}".
                         format(arg_type, str(err)))
             # Test allowed accesses for fields
             if self._function_space1.lower() in DISCONTINUOUS_FUNCTION_SPACES \
                and self._access_descriptor.name.lower() == "gh_inc":
                 raise ParseError(
                     "It does not make sense for a field on a discontinuous "
                     "space ({0}) to have a 'gh_inc' access".
                     format(self._function_space1.lower()))
             # TODO: extend for "gh_write"
             if self._function_space1.lower() in CONTINUOUS_FUNCTION_SPACES \
                and self._access_descriptor.name.lower() == "gh_readwrite":
                 raise ParseError(
                     "It does not make sense for a field on a continuous "
                     "space ({0}) to have a 'gh_readwrite' access".
                     format(self._function_space1.lower()))
             # TODO: extend for "gh_write"
             if self._function_space1.lower() in VALID_ANY_SPACE_NAMES \
                and self._access_descriptor.name.lower() == "gh_readwrite":
                 raise ParseError(
                     "In the dynamo0.3 API a field on any_space cannot "
                     "have 'gh_readwrite' access because it is treated "
                     "as continuous")
             if stencil and self._access_descriptor.name.lower() != "gh_read":
                 raise ParseError("a stencil must be read only so its access"
                                  "should be gh_read")
         # Operators
         elif self._type in VALID_OPERATOR_NAMES:
             # we expect 4 arguments with the 3rd and 4th each being a
             # function space
             if len(arg_type.args) != 4:
                 raise ParseError(
                     "In the dynamo0.3 API each meta_arg entry must have 4 "
                     "arguments if its first argument is gh_operator or "
                     "gh_columnwise_operator, but "
                     "found {0} in '{1}'".format(len(arg_type.args), arg_type))
             if arg_type.args[2].name not in VALID_FUNCTION_SPACE_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API the 3rd argument of a meta_arg "
                     "entry must be a valid function space name (one of {0}), "
                     "but found '{1}' in '{2}".
                     format(VALID_FUNCTION_SPACE_NAMES, arg_type.args[2].name,
                            arg_type))
             self._function_space1 = arg_type.args[2].name
             if arg_type.args[3].name not in VALID_FUNCTION_SPACE_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API the 4th argument of a meta_arg "
                     "entry must be a valid function space name (one of {0}), "
                     "but found '{1}' in '{2}".
                     format(VALID_FUNCTION_SPACE_NAMES, arg_type.args[2].name,
                            arg_type))
             self._function_space2 = arg_type.args[3].name
             # Test allowed accesses for operators
             if self._access_descriptor.name.lower() == "gh_inc":
                 raise ParseError(
                     "In the dynamo0.3 API operators cannot have a 'gh_inc' "
                     "access because they behave as discontinuous quantities")
         # Scalars
         elif self._type in VALID_SCALAR_NAMES:
             if len(arg_type.args) != 2:
                 raise ParseError(
                     "In the dynamo0.3 API each meta_arg entry must have 2 "
                     "arguments if its first argument is gh_{{r,i}}scalar, but "
                     "found {0} in '{1}'".format(len(arg_type.args), arg_type))
             # Test allowed accesses for scalars (read_only or reduction)
             if self._access_descriptor.name not in ["gh_read"] + \
                VALID_REDUCTION_NAMES:
                 raise ParseError(
                     "In the dynamo0.3 API scalar arguments must be "
                     "read-only (gh_read) or a reduction ({0}) but found "
                     "'{1}' in '{2}'".format(VALID_REDUCTION_NAMES,
                                             self._access_descriptor.name,
                                             arg_type))
             # Scalars don't have a function space
             self._function_space1 = None
         # We should never get to here
         else:
             raise ParseError(
                 "Internal error in DynArgDescriptor03.__init__, (2) should "
                 "not get to here")
         Descriptor.__init__(self, self._access_descriptor.name,
                             self._function_space1, stencil=stencil,
                             mesh=mesh)
Member Function Documentation
def psyclone.dynamo0p3.DynArgDescriptor03.function_space (self)
Return the function space name that this instance operates
on. In the case of a gh_operator/gh_columnwise_operator, where there
are 2 function spaces, return function_space_from.
Definition at line 767 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._function_space1, psyclone.dynamo0p3.DynArgDescriptor03._function_space2, and psyclone.dynamo0p3.DynArgDescriptor03._type.
     def function_space(self):
         ''' Return the function space name that this instance operates
         on. In the case of a gh_operator/gh_columnwise_operator, where there
         are 2 function spaces, return function_space_from. '''
         if self._type == "gh_field":
             return self._function_space1
         elif self._type in VALID_OPERATOR_NAMES:
             return self._function_space2
         elif self._type in VALID_SCALAR_NAMES:
             return None
         else:
             raise RuntimeError(
                 "Internal error, DynArgDescriptor03:function_space(), should "
                 "not get to here.")
def psyclone.dynamo0p3.DynArgDescriptor03.function_space_from (self)
Return the "from" function space for a gh_operator. This is
the second function space specified in the metadata. Raise an
error if this is not an operator.
Definition at line 755 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._function_space2, and psyclone.dynamo0p3.DynArgDescriptor03._type.
     def function_space_from(self):
         ''' Return the "from" function space for a gh_operator. This is
         the second function space specified in the metadata. Raise an
         error if this is not an operator. '''
         if self._type in VALID_OPERATOR_NAMES:
             return self._function_space2
         else:
             raise RuntimeError(
                 "function_space_from only makes sense for one of {0}, but this"
                 " is a '{1}'".format(VALID_OPERATOR_NAMES, self._type))
def psyclone.dynamo0p3.DynArgDescriptor03.function_space_to (self)
Return the "to" function space for a gh_operator. This is
the first function space specified in the metadata. Raise an
error if this is not an operator.
Definition at line 743 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._function_space1, and psyclone.dynamo0p3.DynArgDescriptor03._type.
     def function_space_to(self):
         ''' Return the "to" function space for a gh_operator. This is
         the first function space specified in the metadata. Raise an
         error if this is not an operator. '''
         if self._type in VALID_OPERATOR_NAMES:
             return self._function_space1
         else:
             raise RuntimeError(
                 "function_space_to only makes sense for one of {0}, but "
                 "this is a '{1}'".format(VALID_OPERATOR_NAMES, self._type))
def psyclone.dynamo0p3.DynArgDescriptor03.function_spaces (self)
Return the function space names that this instance operates
on as a list. In the case of a gh_operator, where there are 2 function
spaces, we return both.
Definition at line 783 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._type, psyclone.dynamo0p1.DynKernelArgument.function_space(), psyclone.dynamo0p3.DynArgDescriptor03.function_space(), psyclone.dynamo0p3.DynArgDescriptor03.function_space_from(), and psyclone.dynamo0p3.DynArgDescriptor03.function_space_to().
     def function_spaces(self):
         ''' Return the function space names that this instance operates
         on as a list. In the case of a gh_operator, where there are 2 function
         spaces, we return both. '''
         if self._type == "gh_field":
             return [self.function_space]
         elif self._type in VALID_OPERATOR_NAMES:
             # return to before from to maintain expected ordering
             return [self.function_space_to, self.function_space_from]
         elif self._type in VALID_SCALAR_NAMES:
             return []
         else:
             raise RuntimeError(
                 "Internal error, DynArgDescriptor03:function_spaces(), should "
                 "not get to here.")
def psyclone.dynamo0p3.DynArgDescriptor03.type (self)
returns the type of the argument (gh_field, gh_operator, ...).
Definition at line 806 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._access_descriptor, psyclone.dynamo0p3.DynArgDescriptor03._arg_type, psyclone.dynamo0p3.DynArgDescriptor03._function_space1, psyclone.dynamo0p3.DynArgDescriptor03._function_space2, psyclone.dynamo0p3.DynArgDescriptor03._type, and psyclone.dynamo0p3.DynArgDescriptor03._vector_size.
     def type(self):
         ''' returns the type of the argument (gh_field, gh_operator, ...). '''
         return self._type
def psyclone.dynamo0p3.DynArgDescriptor03.vector_size (self)
Returns the vector size of the argument. This will be 1 if *n
has not been specified.
Definition at line 800 of file dynamo0p3.py.
References psyclone.dynamo0p3.DynArgDescriptor03._vector_size.
     def vector_size(self):
         ''' Returns the vector size of the argument. This will be 1 if *n
         has not been specified. '''
         return self._vector_size
The documentation for this class was generated from the following file:
src/psyclone/dynamo0p3.py