#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014.
# However, it has been created with the help of the GungHo Consortium,
# whose members are identified at https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Installs PSyclone from a working copy to a specified location.

This is a very simple install script, not meant to recreat the functionality
of the standard Python install methods. It is supposed to be simple.
'''
from __future__ import print_function

import argparse
import os
import os.path
import shutil
import stat

def install( root ):
    '''
    Performs the install.

    If the install directory does not exist it will be created.

    root [in] (string) Filename of directory into which to install.
    '''
    if not os.path.exists( root ):
        os.makedirs( root )
    else:
        raise Exception( 'Installation directory already exists' )

    ignores = shutil.ignore_patterns( 'tests', 'generator.py' )
    shutil.copytree( 'src', os.path.join( root, 'psyclone' ), \
                     ignore=ignores )

    os.mkdir( os.path.join( root, 'bin' ) )
    shutil.copyfile( os.path.join( 'src', 'generator.py' ), \
                     os.path.join( root, 'bin', 'psyclone' ) )
    os.chmod( os.path.join( root, 'bin', 'psyclone' ), \
              stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR \
              | stat.S_IRGRP | stat.S_IXGRP \
              | stat.S_IROTH | stat.S_IXOTH )

    ignores = shutil.ignore_patterns( 'tests' )
    shutil.copytree( 'f2py_93', \
                     os.path.join( root, 'f2py_93' ), ignore=ignores )

if __name__ == '__main__':
    parser = argparse.ArgumentParser( add_help=False, \
                                      description='Install PSyclone to disc.' )
    parser.add_argument( 'directory', help='Filename for installation root' )
    parser.add_argument( '-help', '-h', '--help', action='help' )
    arguments = parser.parse_args()

    install( arguments.directory )
