# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

# Top-level Makefile to test all the hands-on tutorials for transforming
# generic code.

TUTORIALS = $(sort $(dir $(wildcard */)))

include ./top_level.mk
