# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2022-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

'''
This module defines a Sphinx plugin which enables the use of a
':ref_guide:' role within Sphinx documentation. The link targets
are then generated using the 'ref_guide_base' (configuration
variable) as a base. This is set in the 'conf.py' of the documentation
and enables link targets to be configured at build time.

'''
from docutils import nodes, utils


def setup(app):
    '''
    Sets-up this Sphinx plugin.

    :param app: the Sphinx application object.
    :type app: :py:class:`sphinx.application.Sphinx`

    '''
    # The interface to the handler is defined by Sphinx and we don't
    # use all of the arguments.
    # pylint: disable=unused-argument,too-many-arguments
    def ref_link_role(role, rawtext, text, lineno, inliner, options=None,
                      content=None):
        '''
        Handler routine called when the ':ref_guide:' role is encountered.

        Modifies the supplied link text by appending the given text to
        `../_autogenerated/autoapi/`

        '''
        if not options:
            options = {}
        if not content:
            content = []

        items = text.split()
        ref = "../_autogenerated/autoapi/" + items[-1]
        if len(items) > 1:
            # The link had a name associated with it so reconstruct it.
            name = ' '.join(items[:-1])
        else:
            name = utils.unescape(ref)
        # Construct the new reference.
        node = nodes.reference(rawtext, name, refuri=ref, **options)
        return [node], []

    # Define the new role and assign it our new handler.
    app.add_role('ref_guide', ref_link_role)
