!-----------------------------------------------------------------------------
! (C) Crown copyright 2021 Met Office. All rights reserved.
! The file LICENCE, distributed with this code, contains details of the terms
! under which the code may be used.
!-----------------------------------------------------------------------------

!> @brief Contains a variety of algebra routines for operator types
!!        equivalent to the builtins for fields provided by PSyclone.
!!        This kernel is a template for ones that could be generated by
!!        PSyclone and documented in issue 1099.
module operator_setval_x_kernel_mod

use constants_mod, only: r_def, i_def
use kernel_mod,    only: kernel_type
use argument_mod,  only: arg_type, func_type,        &
                         GH_OPERATOR, GH_SCALAR,     &
                         GH_REAL, GH_READ, GH_WRITE, &
                         ANY_SPACE_1, ANY_SPACE_2,   &
                         ANY_SPACE_3,                    &
                         CELL_COLUMN
implicit none

private

!-------------------------------------------------------------------------------
! Public types
!-------------------------------------------------------------------------------

type, public, extends(kernel_type) :: operator_setval_x_kernel_type
  private
  type(arg_type) :: meta_args(2) = (/                                      &
       arg_type(GH_OPERATOR, GH_REAL, GH_WRITE, ANY_SPACE_1, ANY_SPACE_2), &
       arg_type(GH_OPERATOR, GH_REAL, GH_READ,  ANY_SPACE_1, ANY_SPACE_2)  &
       /)
  integer :: operates_on = CELL_COLUMN
contains
  procedure, nopass :: operator_setval_x_kernel_code
end type

!-------------------------------------------------------------------------------
! Contained functions/subroutines
!-------------------------------------------------------------------------------
public :: operator_setval_x_kernel_code

contains

!> @brief Computes x = y, where x and y are operators.
!! @param[in]     cell       Cell number
!! @param[in]     nlayers    Number of layers
!! @param[in]     ncell_3d_1 Number of 3D cells for x
!! @param[in,out] x          Operator to compute
!! @param[in]     ncell_3d_2 Number of 3D cells for y
!! @param[in]     y          Operator to copy
!! @param[in]     ndf1       Number of dofs per cell for space 1
!! @param[in]     ndf2       Number of dofs per cell for space 2
subroutine operator_setval_x_kernel_code(cell, nlayers, &
                                         ncell_3d_1, x, &
                                         ncell_3d_2, y, &
                                         ndf1, ndf2)
  implicit none

  ! Arguments
  integer(kind=i_def), intent(in) :: cell
  integer(kind=i_def), intent(in) :: nlayers
  integer(kind=i_def), intent(in) :: ncell_3d_1, ncell_3d_2
  integer(kind=i_def), intent(in) :: ndf1, ndf2

  real(kind=r_def), dimension(ndf1, ndf2, ncell_3d_1), intent(inout) :: x
  real(kind=r_def), dimension(ndf1, ndf2, ncell_3d_2), intent(in)    :: y

  ! Internal variables
  integer(kind=i_def) :: k, ik

  do k = 0, nlayers - 1
    ik = k + 1 + (cell-1)*nlayers
    x(:,:,ik) = y(:,:,ik)
  end do

end subroutine operator_setval_x_kernel_code

end module operator_setval_x_kernel_mod
