#!/bin/bash

# abort if a command fails
set -e

echo "Running examples dynamo/eg1"
cd dynamo/eg1
python runme.py
python runme_openmp.py
cd -

echo "Running examples dynamo/eg2"
cd dynamo/eg2
python runme.py
python runme_openmp.py
python runme_loop_fuse.py
cd -

echo "Running example dynamo/eg3"
cd dynamo/eg3
python ../../../src/generator.py solver_mod.x90
python ../../../src/generator.py -s ./colouring_and_omp.py -nodm solver_mod.x90
cd -

echo "Running example dynamo/eg4"
cd dynamo/eg4
python ../../../src/generator.py -nodm solver_mod.x90
python ../../../src/generator.py solver_mod.x90
cd -

echo "Running example dynamo/eg5"
cd dynamo/eg5
python ../../../src/generator.py alg.f90
cd -

echo "Running gocean examples"
cd gocean
python runme.py
python runme_openmp.py
python runme_loop_fuse.py
cd -

echo "Running transformation examples"
cd transformations/inline
python module_inline_example.py
cd -

echo "Running line-length examples"
cd line_length
python runme.py
cd -

echo "Running stub generation examples"
cd stub_generation
python ../../src/genkernelstub.py testkern_stencil_multi_mod.f90
cd -
