# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

# Setting for the PSyData value range check library
PSYDATA_PATH?=$(PSYCLONE_RELPATH)/lib/value_range_check/lfric
PSYDATA_LIB_NAME?=_value_range_check

include Makefile.inc

time_evolution_alg_mod_psy.f90: time_evolution_alg_mod.x90 solutions/value_range_check_all_transform.py
	psyclone $(PSYCLONE_CMD)                                   \
	-d . -d ../gungho_lib                                      \
	-s ./solutions/value_range_check_all_transform.py          \
	-opsy time_evolution_alg_mod_psy.f90                       \
	-oalg time_evolution_alg_mod.f90 time_evolution_alg_mod.x90

