# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

# Setting for the PSyData readonly verification library
PSYDATA_PATH?=$(PSYCLONE_RELPATH)/lib/read_only/lfric
PSYDATA_LIB_NAME?=_read_only

include Makefile.inc

time_evolution_alg_mod_psy.f90: time_evolution_alg_mod.x90 solutions/readonly_all_transform.py
	psyclone $(PSYCLONE_CMD) -s ./solutions/readonly_all_transform.py \
	-d . -d ../gungho_lib                                             \
	-opsy time_evolution_alg_mod_psy.f90                              \
	-oalg time_evolution_alg_mod.f90 time_evolution_alg_mod.x90

