# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

include ../common.mk

transform:
	${KERNEL_STUB_GEN} -api lfric testkern_stencil_multi_mod.f90

compile:
	@echo "No compilation supported for stub-generation example"

run: compile
	@echo "No run targets for stub-generation example"
