# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Science and Technology
#                         Facilities Council
# SPDX-License-Identifier: BSD-3-Clause
# See the full LICENSE file in the project root for details.
# -----------------------------------------------------------------------------

# Setting for the PSyData extraction library
TYPE?=netcdf
PSYDATA_PATH?=$(PSYCLONE_RELPATH)/lib/extract/$(TYPE)/lfric
PSYDATA_LIB_NAME?=_extract
PSYROOT=../../../../..

default: new_default

include Makefile.inc

new_default: $(EXEC) driver-time_evolution-propagate

driver-time_evolution-propagate: driver-time_evolution-propagate.o
       $(F90) $(FFLAGS) driver-time_evolution-propagate.o -o driver-time_evolution-propagate

time_evolution_alg_mod_psy.f90: time_evolution_alg_mod.x90 extract_one_transform.py
	psyclone $(PSYCLONE_CMD)                                                   \
    -d . -d ../gungho_lib -d $(PSYROOT)/lib/extract/$(TYPE)/lfric                 \
    -d ../../../../../external/lfric_infrastructure/src                           \
    -opsy time_evolution_alg_mod_psy.f90                                          \
    -oalg time_evolution_alg_mod.f90 time_evolution_alg_mod.x90

