# run (which is usually compilation tests) should also run
# the normal tests (so all is tested during integration tests)
run test:
	./handle_fortran.py
	./var_access.py
	./sympy_test.py
	./dataflow.py

compile:
	# Nothing to compile here

clean:
	# Nothing to clean here