name: Linkspector
on: [pull_request]
jobs:
  check-links:
    if: ${{ github.repository != 'stfc/PSyclone-mirror' }}
    name: Run linkspector
    # TODO 2838: linkspector doesn't support ubuntu-latest at the moment.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          config_file: '.github/linkspector.yml'
